// Generated by `pnpm --filter @zemd/gha run build` from internal/gha/src. Do not edit.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { execFileSync } from "node:child_process";

//#region src/semver.ts
const SEMVER = /^\d+\.\d+\.\d+$/;
const isReleaseVersion = (version) => SEMVER.test(version);
const parseVersion = (version) => {
	const [core = "", ...prerelease] = version.split("-");
	const [major = 0, minor = 0, patch = 0] = core.split(".").map(Number);
	return {
		major,
		minor,
		patch,
		prerelease: prerelease.join("-")
	};
};
const bumpType = (from, to) => {
	const a = parseVersion(from);
	const b = parseVersion(to);
	if (b.prerelease || a.prerelease) return "prerelease";
	if (b.major !== a.major) return "major";
	if (b.minor !== a.minor) return "minor";
	return "patch";
};

//#endregion
//#region src/contract-version.ts
const BUMP_PRIORITY = {
	patch: 0,
	minor: 1,
	major: 2
};
const scalar = (value) => {
	const trimmed = value.trim();
	const quote = trimmed.at(0);
	if ((quote === "\"" || quote === "'") && trimmed.at(-1) === quote) return trimmed.slice(1, -1);
	return trimmed;
};
const frontmatter = (source) => {
	return source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)?.[1] ?? "";
};
const packageBump = (source, packageName) => {
	for (const line of frontmatter(source).split(/\r?\n/)) {
		const separator = line.indexOf(":");
		if (separator < 0 || scalar(line.slice(0, separator)) !== packageName) continue;
		const bump = scalar(line.slice(separator + 1));
		if (bump === "major" || bump === "minor" || bump === "patch") return bump;
	}
};
const bumpContractVersion = (version, bump) => {
	if (!isReleaseVersion(version)) throw new Error(`contract version must be plain semver, got "${version}"`);
	const parsed = parseVersion(version);
	if (bump === "major") return `${parsed.major + 1}.0.0`;
	if (bump === "minor") return `${parsed.major}.${parsed.minor + 1}.0`;
	return `${parsed.major}.${parsed.minor}.${parsed.patch + 1}`;
};
const planContractVersion = (manifest, intents) => {
	const releases = intents.flatMap((intent) => {
		const bump = packageBump(intent.source, manifest.name);
		return bump === void 0 ? [] : [{
			id: intent.id,
			bump
		}];
	});
	if (releases.length === 0) return void 0;
	const bump = releases.reduce((highest, release) => BUMP_PRIORITY[release.bump] > BUMP_PRIORITY[highest] ? release.bump : highest, releases[0]?.bump ?? "patch");
	return {
		name: manifest.name,
		currentVersion: manifest.version,
		newVersion: bumpContractVersion(manifest.version, bump),
		bump,
		intentIds: releases.map(({ id }) => id).sort()
	};
};
const reconcileContractRelease = (releases, plan) => {
	const matching = releases.filter(({ name }) => name === plan.name);
	if (matching.length !== 1) throw new Error(`pnpm version reported ${matching.length} releases for ${plan.name}; expected exactly one`);
	const release = matching[0];
	if (!release) throw new Error(`pnpm version did not report ${plan.name}`);
	if (release.currentVersion === plan.currentVersion && release.newVersion === plan.newVersion) return releases;
	if (release.currentVersion !== plan.newVersion || release.newVersion !== plan.newVersion) throw new Error(`pnpm version reported an unexpected ${plan.name} transition: ${release.currentVersion} -> ${release.newVersion}; expected ${plan.newVersion} -> ${plan.newVersion}`);
	return releases.map((entry) => entry === release ? {
		...entry,
		currentVersion: plan.currentVersion
	} : entry);
};

//#endregion
//#region src/pnpm.ts
const asArray = (value, context) => {
	if (!Array.isArray(value)) throw new Error(`${context}: expected an array, got ${typeof value}`);
	return value;
};
const asRecord = (value, context) => {
	if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${context}: expected an object, got ${JSON.stringify(value)}`);
	return value;
};
const asString = (source, key, context) => {
	const value = source[key];
	if (typeof value !== "string") throw new Error(`${context}: expected "${key}" to be a string, got ${JSON.stringify(value)}`);
	return value;
};
const parseAppliedReleases = (json) => asArray(JSON.parse(json), "pnpm version -r --json").map((entry, index) => {
	const context = `pnpm version -r --json[${index}]`;
	const record = asRecord(entry, context);
	return {
		name: asString(record, "name", context),
		currentVersion: asString(record, "currentVersion", context),
		newVersion: asString(record, "newVersion", context)
	};
});
const parseWorkspacePackages = (json) => asArray(JSON.parse(json), "pnpm list -r --json").map((entry, index) => {
	const context = `pnpm list -r --json[${index}]`;
	const record = asRecord(entry, context);
	return {
		name: asString(record, "name", context),
		version: asString(record, "version", context),
		path: asString(record, "path", context),
		private: record["private"] === true
	};
});
const parsePublishSummary = (json) => {
	const published = asRecord(JSON.parse(json), "pnpm publish --report-summary")["publishedPackages"];
	if (published === void 0) return [];
	return asArray(published, "pnpm publish --report-summary.publishedPackages").map((entry, index) => {
		const context = `pnpm publish --report-summary.publishedPackages[${index}]`;
		const record = asRecord(entry, context);
		return {
			name: asString(record, "name", context),
			version: asString(record, "version", context)
		};
	});
};

//#endregion
//#region src/commands/contract-version.ts
const parseManifest = (source, path) => {
	const value = JSON.parse(source);
	if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${path}: expected a package manifest object`);
	const manifest = value;
	if (typeof manifest["name"] !== "string" || typeof manifest["version"] !== "string") throw new Error(`${path}: expected string name and version fields`);
	if (manifest["private"] !== true) throw new Error(`${path}: contract version preparation is restricted to private packages`);
	return {
		name: manifest["name"],
		version: manifest["version"],
		private: true
	};
};
const replaceManifestVersion = (source, currentVersion, newVersion, path) => {
	const property = /("version"\s*:\s*")([^"]*)(")/g;
	const matches = [...source.matchAll(property)];
	if (matches.length !== 1 || matches[0]?.[2] !== currentVersion) throw new Error(`${path}: could not replace the unique version field`);
	return source.replace(property, `$1${newVersion}$3`);
};
const readIntents = (directory) => readdirSync(directory).filter((file) => file.endsWith(".md") && file.toLowerCase() !== "readme.md").sort().map((file) => ({
	id: basename(file, ".md"),
	source: readFileSync(join(directory, file), "utf8")
}));
const parsePlan = (source, path) => {
	const value = JSON.parse(source);
	if (value === null) return void 0;
	if (typeof value !== "object" || Array.isArray(value)) throw new Error(`${path}: expected a contract version plan or null`);
	const plan = value;
	const bump = plan["bump"];
	if (typeof plan["name"] !== "string" || typeof plan["currentVersion"] !== "string" || typeof plan["newVersion"] !== "string" || bump !== "major" && bump !== "minor" && bump !== "patch" || !Array.isArray(plan["intentIds"]) || !plan["intentIds"].every((id) => typeof id === "string")) throw new Error(`${path}: invalid contract version plan`);
	return {
		name: plan["name"],
		currentVersion: plan["currentVersion"],
		newVersion: plan["newVersion"],
		bump,
		intentIds: plan["intentIds"]
	};
};
const prepare$1 = (packagePath, intentsDirectory, statePath) => {
	const manifestSource = readFileSync(packagePath, "utf8");
	const manifest = parseManifest(manifestSource, packagePath);
	const plan = planContractVersion(manifest, readIntents(intentsDirectory));
	writeFileSync(statePath, `${JSON.stringify(plan ?? null, void 0, 2)}\n`);
	if (!plan) return;
	writeFileSync(packagePath, replaceManifestVersion(manifestSource, plan.currentVersion, plan.newVersion, packagePath));
};
const finalize = (statePath, releasesPath) => {
	const plan = parsePlan(readFileSync(statePath, "utf8"), statePath);
	if (!plan) return;
	const releases = parseAppliedReleases(readFileSync(releasesPath, "utf8"));
	writeFileSync(releasesPath, `${JSON.stringify(reconcileContractRelease(releases, plan), void 0, 2)}\n`);
};
const contractVersion = {
	usage: "prepare <package.json> <intents-dir> <state.json> | finalize <state.json> <releases.json>",
	run: (argv) => {
		const [operation, firstPath, secondPath, thirdPath] = argv;
		if (operation === "prepare" && firstPath && secondPath && thirdPath) {
			prepare$1(firstPath, secondPath, thirdPath);
			return;
		}
		if (operation === "finalize" && firstPath && secondPath && !thirdPath) {
			finalize(firstPath, secondPath);
			return;
		}
		throw new Error("usage: contract-version prepare <package.json> <intents-dir> <state.json> | finalize <state.json> <releases.json>");
	}
};

//#endregion
//#region src/env.ts
const requireEnv = (name) => {
	const value = process.env[name];
	if (!value) throw new Error(`${name} must be set`);
	return value;
};
const optionalEnv = (name, fallback) => {
	const value = process.env[name];
	return value ? value : fallback;
};

//#endregion
//#region src/changelog.ts
const changelogEntry = (packagePath, version) => {
	let changelog;
	try {
		changelog = readFileSync(join(packagePath, "CHANGELOG.md"), "utf8");
	} catch {
		return "";
	}
	const lines = changelog.split("\n");
	const start = lines.findIndex((line) => line.trim().replace(/\s+-\s+\d{4}-\d{2}-\d{2}$/, "").replace(/[[\]]/g, "") === `## ${version}`);
	if (start === -1) return "";
	const rest = lines.slice(start + 1);
	const end = rest.findIndex((line) => line.startsWith("## "));
	return (end === -1 ? rest : rest.slice(0, end)).join("\n").replace(/^#{1,6}\s+(.+)$/gm, "**$1**").trim();
};

//#endregion
//#region src/release-tags.ts
const packageReleaseTag = (name, version) => `${name}@${version}`;

//#endregion
//#region src/github-releases.ts
const RELEASE_TAG_PREFIX = "release-";
const appendPackageTable = (out, heading, packages, approvalRequired) => {
	if (packages.length === 0) return;
	out.push(`## ${heading}`);
	if (approvalRequired) {
		out.push("");
		out.push("These versions require maintainer approval with 2FA before they become available from npm.");
		out.push("Rejecting one does not roll back this release or make its version reusable; release changes under a new version instead.");
	}
	out.push("");
	out.push("| Package | Version |");
	out.push("| :--- | ---: |");
	for (const { name, version } of packages) out.push(`| [\`${name}\`](https://www.npmjs.com/package/${name}) | \`${version}\` |`);
	out.push("");
};
const renderCombinedReleaseBody = ({ published, staged = [], paths, notes }) => {
	const out = [];
	const submitted = [...published, ...staged];
	appendPackageTable(out, "Published packages", published, false);
	appendPackageTable(out, "Packages staged on npm", staged, true);
	out.push("### Changelogs");
	out.push("");
	for (const { name, version } of submitted) {
		const packagePath = paths.get(name);
		out.push("<details>");
		out.push(`<summary><code>${name}@${version}</code></summary>`);
		out.push("");
		out.push("<br>");
		out.push("");
		out.push((packagePath ? changelogEntry(packagePath, version) : "") || "_No changelog entry recorded._");
		out.push("");
		out.push("</details>");
		out.push("");
	}
	if (notes?.trim()) {
		out.push("---");
		out.push("");
		out.push(notes.trim());
	}
	return out.join("\n").trim();
};
const nextReleaseTag = async (api, now) => {
	const stamp = now.toISOString().slice(0, 16).replace("T", "-").replace(":", "");
	const base = `${RELEASE_TAG_PREFIX}${stamp}`;
	for (let counter = 1; counter < 100; counter += 1) {
		const tag = counter === 1 ? base : `${base}.${counter}`;
		if (!await api.tagExists(tag)) return tag;
	}
	throw new Error(`could not find a free release tag for ${base}`);
};
const previousReleaseTag = async (api) => {
	return (await api.listReleases()).filter((release) => release.tag_name.startsWith(RELEASE_TAG_PREFIX)).sort((a, b) => b.created_at.localeCompare(a.created_at))[0]?.tag_name ?? "";
};
const createTag = async (api, tag, sha) => {
	const response = await api.createRef(`refs/tags/${tag}`, sha);
	if (response.ok) {
		console.log(`created tag ${tag}`);
		return true;
	}
	if (response.status === 422 && await api.tagExists(tag)) {
		console.log(`tag ${tag} already exists, skipping`);
		return true;
	}
	console.error(`failed to create tag ${tag}:`, response.payload);
	return false;
};
const releasePublishedPackages = async ({ api, sha, published, staged = [], workspace, now = /* @__PURE__ */ new Date() }) => {
	if (published.length === 0 && staged.length === 0) {
		console.log("no packages were submitted to npm, nothing to release");
		return;
	}
	const publishedReleases = [...published].sort((a, b) => a.name.localeCompare(b.name));
	const stagedReleases = [...staged].sort((a, b) => a.name.localeCompare(b.name));
	const releases = [...publishedReleases, ...stagedReleases].sort((a, b) => a.name.localeCompare(b.name));
	const paths = new Map(workspace.map((entry) => [entry.name, entry.path]));
	let failed = false;
	for (const { name, version } of releases) if (!await createTag(api, packageReleaseTag(name, version), sha)) failed = true;
	const releaseTag = await nextReleaseTag(api, now);
	const notes = await api.generateNotes(releaseTag, sha, await previousReleaseTag(api));
	const created = await api.createRelease({
		tag: releaseTag,
		name: releaseTag,
		targetCommitish: sha,
		body: renderCombinedReleaseBody({
			published: publishedReleases,
			staged: stagedReleases,
			paths,
			notes
		}),
		prerelease: releases.every(({ version }) => version.includes("-"))
	});
	if (created.ok) console.log(`created release ${releaseTag}`);
	else {
		failed = true;
		console.error(`failed to create release ${releaseTag}:`, created.payload);
	}
	if (failed) throw new Error("one or more release steps failed");
};

//#endregion
//#region src/github.ts
const COMMIT_MUTATION = `
    mutation ($input: CreateCommitOnBranchInput!) {
      createCommitOnBranch(input: $input) {
        commit {
          oid
        }
      }
    }
  `;
const createGitHubApi = (options) => {
	const { token, repository } = options;
	const apiUrl = options.apiUrl ?? "https://api.github.com";
	const graphqlUrl = options.graphqlUrl ?? "https://api.github.com/graphql";
	const doFetch = options.fetch ?? globalThis.fetch;
	const requestUrl = async (url, method, body) => {
		const response = await doFetch(url, {
			method,
			headers: {
				accept: "application/vnd.github+json",
				authorization: `Bearer ${token}`,
				"content-type": "application/json",
				"x-github-api-version": "2022-11-28"
			},
			...body === void 0 ? {} : { body: JSON.stringify(body) }
		});
		const text = await response.text();
		return {
			ok: response.ok,
			status: response.status,
			payload: text ? JSON.parse(text) : {}
		};
	};
	const request = (path, method, body) => requestUrl(`${apiUrl}${path}`, method, body);
	const api = {
		repository,
		request,
		graphql: (query, variables) => requestUrl(graphqlUrl, "POST", {
			query,
			variables
		}),
		tagExists: async (tag) => {
			const response = await request(`/repos/${repository}/git/ref/tags/${encodeURIComponent(tag)}`, "GET");
			if (response.status === 404) return false;
			if (!response.ok) throw new Error(`failed to check git tag "${tag}": GitHub returned ${response.status}`);
			return true;
		},
		createRef: (ref, sha) => request(`/repos/${repository}/git/refs`, "POST", {
			ref,
			sha
		}),
		updateRef: (ref, sha) => request(`/repos/${repository}/git/${ref}`, "PATCH", {
			sha,
			force: true
		}),
		listReleases: async () => {
			const response = await request(`/repos/${repository}/releases?per_page=100`, "GET");
			return response.ok ? response.payload : [];
		},
		generateNotes: async (tag, sha, previousTag) => {
			const response = await request(`/repos/${repository}/releases/generate-notes`, "POST", {
				tag_name: tag,
				target_commitish: sha,
				...previousTag ? { previous_tag_name: previousTag } : {}
			});
			if (!response.ok) {
				console.warn(`failed to generate notes for ${tag}:`, response.payload);
				return "";
			}
			return (response.payload.body ?? "").trim();
		},
		createRelease: (release) => request(`/repos/${repository}/releases`, "POST", {
			tag_name: release.tag,
			name: release.name,
			body: release.body,
			draft: false,
			prerelease: release.prerelease,
			...release.targetCommitish === void 0 ? {} : { target_commitish: release.targetCommitish }
		}),
		createCommitOnBranch: async (branch, expectedHeadOid, message, fileChanges) => {
			const [headline, ...body] = message.split("\n\n");
			const rest = body.join("\n\n");
			const result = await api.graphql(COMMIT_MUTATION, { input: {
				branch: {
					repositoryNameWithOwner: repository,
					branchName: branch
				},
				expectedHeadOid,
				message: {
					headline,
					...rest ? { body: rest } : {}
				},
				fileChanges
			} });
			const oid = result.payload.data?.createCommitOnBranch.commit.oid;
			if (!result.ok || result.payload.errors || !oid) throw new Error(`failed to create commit: ${JSON.stringify(result.payload.errors ?? result.payload)}`);
			return oid;
		}
	};
	return api;
};

//#endregion
//#region src/commands/context.ts
const apiFromEnv = () => createGitHubApi({
	token: requireEnv("GITHUB_TOKEN"),
	repository: requireEnv("GITHUB_REPOSITORY"),
	apiUrl: optionalEnv("GITHUB_API_URL", "https://api.github.com"),
	graphqlUrl: optionalEnv("GITHUB_GRAPHQL_URL", "https://api.github.com/graphql")
});

//#endregion
//#region src/commands/github-releases.ts
const readSummary = (path) => existsSync(path) ? parsePublishSummary(readFileSync(path, "utf8")) : [];
const githubReleases = {
	usage: "<published-summary.json> <staged-summary.json> <workspace-list.json>",
	run: async (argv) => {
		const [publishedSummaryPath, stagedSummaryPath, workspacePath] = argv;
		if (!publishedSummaryPath || !stagedSummaryPath || !workspacePath) throw new Error("usage: github-releases <published-summary.json> <staged-summary.json> <workspace-list.json>");
		await releasePublishedPackages({
			api: apiFromEnv(),
			sha: requireEnv("GITHUB_SHA"),
			published: readSummary(publishedSummaryPath),
			staged: readSummary(stagedSummaryPath),
			workspace: parseWorkspacePackages(readFileSync(workspacePath, "utf8"))
		});
	}
};

//#endregion
//#region src/npm-publishing.ts
const packageUrl = (registryUrl, packageName) => {
	const registry = new URL(registryUrl);
	if (!registry.pathname.endsWith("/")) registry.pathname += "/";
	const encodedName = encodeURIComponent(packageName).replace(/^%40/, "@");
	return new URL(encodedName, registry);
};
const packageExistsOnRegistry = async (packageName, registryUrl, request) => {
	const response = await request(packageUrl(registryUrl, packageName), { headers: { accept: "application/vnd.npm.install-v1+json" } });
	if (response.status === 404) return false;
	if (!response.ok) {
		const status = response.statusText ? `${response.status} ${response.statusText}` : String(response.status);
		throw new Error(`npm registry lookup for "${packageName}" failed: ${status}`);
	}
	return true;
};
const planNpmPublishing = async (workspace, stagedPublishing, packageExists, releaseTagExists) => {
	const publicPackages = workspace.filter((workspacePackage) => !workspacePackage.private);
	const submissionState = await Promise.all(publicPackages.map(async (workspacePackage) => ({
		workspacePackage,
		submitted: await releaseTagExists(packageReleaseTag(workspacePackage.name, workspacePackage.version))
	})));
	const previouslySubmittedPackages = submissionState.filter(({ submitted }) => submitted).map(({ workspacePackage: { name, version } }) => ({
		name,
		version
	}));
	const pendingPackages = submissionState.filter(({ submitted }) => !submitted).map(({ workspacePackage }) => workspacePackage);
	const existence = await Promise.all(pendingPackages.map(async (workspacePackage) => ({
		name: workspacePackage.name,
		exists: await packageExists(workspacePackage.name)
	})));
	const firstReleasePackages = existence.filter(({ exists }) => !exists).map(({ name }) => name);
	const directPackages = stagedPublishing ? firstReleasePackages : existence.map(({ name }) => name);
	const stagedPackages = stagedPublishing ? existence.filter(({ exists }) => exists).map(({ name }) => name) : [];
	let mode;
	if (directPackages.length > 0) mode = stagedPackages.length > 0 ? "mixed" : "direct";
	else if (stagedPackages.length > 0) mode = "staged";
	else mode = "none";
	return {
		mode,
		directPackages,
		firstReleasePackages,
		previouslySubmittedPackages,
		stagedPackages
	};
};

//#endregion
//#region src/commands/npm-publishing-mode.ts
const parseBoolean = (value) => {
	if (value === "true") return true;
	if (value === "false") return false;
	throw new Error(`npm-publishing-mode: expected "true" or "false", got "${value}"`);
};
const npmPublishingMode = {
	usage: "<workspace-list.json> <registry-url> <staged-publishing> <first-releases.txt> <direct-packages.txt> <staged-packages.txt>",
	run: async (argv) => {
		const [workspacePath, registryUrl, rawStagedPublishing, firstReleasesPath, directPackagesPath, stagedPackagesPath] = argv;
		if (!workspacePath || !registryUrl || !rawStagedPublishing || !firstReleasesPath || !directPackagesPath || !stagedPackagesPath) throw new Error("usage: npm-publishing-mode <workspace-list.json> <registry-url> <staged-publishing> <first-releases.txt> <direct-packages.txt> <staged-packages.txt>");
		const stagedPublishing = parseBoolean(rawStagedPublishing);
		const api = apiFromEnv();
		const plan = await planNpmPublishing(parseWorkspacePackages(readFileSync(workspacePath, "utf8")), stagedPublishing, (packageName) => packageExistsOnRegistry(packageName, registryUrl, (url, init) => fetch(url, { headers: init.headers })), (tag) => api.tagExists(tag));
		if (plan.previouslySubmittedPackages.length > 0) console.error(`Skipping versions already recorded by immutable release tags: ${plan.previouslySubmittedPackages.map(({ name, version }) => packageReleaseTag(name, version)).join(", ")}`);
		if (plan.firstReleasePackages.length > 0) console.error(`Regular npm publishing is required for first release: ${plan.firstReleasePackages.join(", ")}`);
		writeFileSync(firstReleasesPath, plan.firstReleasePackages.map((packageName) => `${packageName}\n`).join(""));
		writeFileSync(directPackagesPath, plan.directPackages.map((packageName) => `${packageName}\n`).join(""));
		writeFileSync(stagedPackagesPath, plan.stagedPackages.map((packageName) => `${packageName}\n`).join(""));
		process.stdout.write([
			`mode=${plan.mode}`,
			`direct=${plan.directPackages.length > 0}`,
			`stage=${plan.stagedPackages.length > 0}`,
			`first_release=${plan.firstReleasePackages.length > 0}`,
			""
		].join("\n"));
	}
};

//#endregion
//#region src/release-pr-body.ts
const badge = {
	major: "**major**",
	minor: "**minor**",
	patch: "patch",
	prerelease: "prerelease",
	new: "first release"
};
const prepare = (applied, workspace) => {
	const packages = new Map(workspace.map((entry) => [entry.name, entry]));
	return applied.map((release) => {
		const entry = packages.get(release.name);
		if (!entry) throw new Error(`release package ${release.name} is missing from the workspace snapshot`);
		const firstRelease = release.currentVersion === release.newVersion;
		return {
			name: release.name,
			path: entry.path,
			from: firstRelease ? void 0 : release.currentVersion,
			to: release.newVersion,
			kind: firstRelease ? "new" : bumpType(release.currentVersion, release.newVersion),
			internal: entry.private
		};
	}).sort((a, b) => a.name.localeCompare(b.name));
};
const changelogDetails = (out, release) => {
	const transition = release.from ? `${release.from} &rarr; <b>${release.to}</b>` : `<b>${release.to}</b>`;
	out.push("<details>");
	out.push(`<summary><code>${release.name}</code> &nbsp;&middot;&nbsp; ${transition}</summary>`);
	out.push("");
	out.push("<br>");
	out.push("");
	out.push(changelogEntry(release.path, release.to) || "_No changelog entry recorded._");
	out.push("");
	out.push("</details>");
	out.push("");
};
const renderReleasePrBody = (applied, workspace) => {
	const prepared = prepare(applied, workspace);
	const releases = prepared.filter((release) => !release.internal);
	const internal = prepared.filter((release) => release.internal);
	const out = [];
	out.push("## Release summary");
	out.push("");
	if (releases.length === 0) out.push("No publishable packages were prepared for release.");
	else {
		const count = releases.length;
		out.push(`\`pnpm version -r\` consumed the pending change intents and prepared **${count}** package${count === 1 ? "" : "s"} for release.`);
		out.push("Merging this pull request publishes the versions listed below.");
		out.push("");
		out.push("| Package | Bump | Current | Next |");
		out.push("| :--- | :---: | ---: | ---: |");
		for (const release of releases) {
			const current = release.from ? `\`${release.from}\`` : "—";
			out.push(`| \`${release.name}\` | ${badge[release.kind]} | ${current} | \`${release.to}\` |`);
		}
		out.push("");
		out.push("### Changelogs");
		out.push("");
		for (const release of releases) changelogDetails(out, release);
	}
	if (internal.length > 0) {
		out.push("");
		out.push("### Internal packages");
		out.push("");
		out.push("Not published to npm.");
		out.push("");
		out.push("| Package | Bump | Current | Next |");
		out.push("| :--- | :---: | ---: | ---: |");
		for (const release of internal) {
			const current = release.from ? `\`${release.from}\`` : "—";
			out.push(`| \`${release.name}\` | ${badge[release.kind]} | ${current} | \`${release.to}\` |`);
		}
		out.push("");
		for (const release of internal) changelogDetails(out, release);
	}
	out.push("");
	return `${out.join("\n")}\n`;
};

//#endregion
//#region src/commands/release-pr-body.ts
const releasePrBody = {
	usage: "<releases.json> <workspace-list.json>",
	run: (argv) => {
		const [releasesPath, workspacePath] = argv;
		if (!releasesPath || !workspacePath) throw new Error("usage: release-pr-body <releases.json> <workspace-list.json>");
		process.stdout.write(renderReleasePrBody(parseAppliedReleases(readFileSync(releasesPath, "utf8")), parseWorkspacePackages(readFileSync(workspacePath, "utf8"))));
	}
};

//#endregion
//#region src/shared-workflows.ts
const renderSharedReleaseBody = ({ repository, version, sha, workflows, changelog, notes }) => {
	const major = version.split(".")[0];
	const out = [];
	out.push("Shared GitHub Actions workflows. Add one job per workflow to a caller in");
	out.push("`.github/workflows/`, pinned to this commit:");
	out.push("");
	out.push("```yaml");
	for (const workflow of workflows) out.push(`uses: ${repository}/.github/workflows/${workflow}@${sha} # v${version}`);
	out.push("```");
	out.push("");
	out.push(`Ready-to-copy callers: [\`.github/workflows-examples\`](https://github.com/${repository}/tree/${sha}/.github/workflows-examples).`);
	out.push("");
	out.push("Re-resolve this commit at any time:");
	out.push("");
	out.push("```sh");
	out.push(`gh api repos/${repository}/git/ref/tags/v${major} --jq .object.sha`);
	out.push("```");
	if (changelog?.trim()) {
		out.push("");
		out.push("## Changes");
		out.push("");
		out.push(changelog.trim());
	}
	if (notes?.trim()) {
		out.push("");
		out.push("---");
		out.push("");
		out.push(notes.trim());
	}
	return `${out.join("\n")}\n`;
};
const putTag = async (api, tag, sha, force) => {
	const created = await api.createRef(`refs/tags/${tag}`, sha);
	if (created.ok) return true;
	if (!force) {
		console.error(`failed to create tag ${tag}:`, created.payload);
		return false;
	}
	const updated = await api.updateRef(`refs/tags/${tag}`, sha);
	if (updated.ok) return true;
	console.error(`failed to move tag ${tag}:`, updated.payload);
	return false;
};
const releaseSharedWorkflows = async ({ api, sha, version, packagePath, workflows }) => {
	if (!isReleaseVersion(version)) throw new Error(`expected a plain semver version, got "${version}"`);
	if (workflows.length === 0) throw new Error("no shared-*.yml workflows found");
	const tag = `v${version}`;
	const releases = await api.listReleases();
	if (releases.some((release) => release.tag_name === tag)) {
		console.log(`${tag} already released, nothing to do`);
		return;
	}
	if (!await api.tagExists(tag) && !await putTag(api, tag, sha, false)) throw new Error(`could not create ${tag}`);
	if (!await putTag(api, `v${version.split(".")[0]}`, sha, true)) throw new Error(`could not move the major tag for ${tag}`);
	const previousTag = releases.filter((release) => isReleaseVersion(release.tag_name.replace(/^v/, ""))).sort((a, b) => b.created_at.localeCompare(a.created_at))[0]?.tag_name ?? "";
	const created = await api.createRelease({
		tag,
		name: `Shared workflows ${tag}`,
		body: renderSharedReleaseBody({
			repository: api.repository,
			version,
			sha,
			workflows,
			changelog: changelogEntry(packagePath, version),
			notes: await api.generateNotes(tag, sha, previousTag)
		}),
		prerelease: false
	});
	if (!created.ok) throw new Error(`failed to create release ${tag}: ${JSON.stringify(created.payload)}`);
	console.log(`created release ${tag} at ${sha}`);
};

//#endregion
//#region src/commands/shared-workflows-release.ts
const manifestVersion = (packagePath) => {
	const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
	if (typeof manifest !== "object" || manifest === null || !("version" in manifest)) throw new Error(`${packagePath} has no version field`);
	const { version } = manifest;
	if (typeof version !== "string") throw new Error(`${packagePath}: expected a string version, got ${JSON.stringify(version)}`);
	return version;
};
const sharedWorkflowsRelease = {
	usage: "<package.json> <workflows-dir>",
	run: async (argv) => {
		const [packagePath, workflowsDir] = argv;
		if (!packagePath || !workflowsDir) throw new Error("usage: shared-workflows-release <package.json> <workflows-dir>");
		await releaseSharedWorkflows({
			api: apiFromEnv(),
			sha: requireEnv("GITHUB_SHA"),
			version: manifestVersion(packagePath),
			packagePath: dirname(packagePath),
			workflows: readdirSync(workflowsDir).filter((file) => file.startsWith("shared-") && file.endsWith(".yml")).sort()
		});
	}
};

//#endregion
//#region src/signed-commit.ts
const collectChanges = ({ git, read }) => {
	const records = git([
		"status",
		"--porcelain=v1",
		"-z",
		"--untracked-files=all"
	]).split("\0").filter(Boolean);
	const added = /* @__PURE__ */ new Set();
	const deleted = /* @__PURE__ */ new Set();
	for (let index = 0; index < records.length; index += 1) {
		const record = records[index] ?? "";
		const state = record.slice(0, 2);
		const path = record.slice(3);
		if (state.includes("R") || state.includes("C")) {
			const origin = records[index + 1];
			index += 1;
			if (state.includes("R") && origin) deleted.add(origin);
			added.add(path);
			continue;
		}
		if (state.includes("D")) {
			deleted.add(path);
			continue;
		}
		added.add(path);
	}
	const readFile = read ?? ((path) => readFileSync(path));
	return {
		additions: [...added].map((path) => ({
			path,
			contents: readFile(path).toString("base64")
		})),
		deletions: [...deleted].map((path) => ({ path }))
	};
};
const createSignedCommit = async ({ api, git, branch, message, changes }) => {
	if (changes.additions.length === 0 && changes.deletions.length === 0) throw new Error("nothing to commit");
	const baseOid = git(["rev-parse", "HEAD"]).trim();
	const ref = `refs/heads/${branch}`;
	if (!(await api.createRef(ref, baseOid)).ok) {
		const updated = await api.updateRef(ref, baseOid);
		if (!updated.ok) throw new Error(`failed to point ${branch} at ${baseOid}: ${JSON.stringify(updated.payload)}`);
	}
	return api.createCommitOnBranch(branch, baseOid, message, changes);
};

//#endregion
//#region src/commands/signed-commit.ts
const signedCommit = {
	usage: "<branch> <message>",
	run: async (argv) => {
		const [branch, message] = argv;
		if (!branch || !message) throw new Error("usage: signed-commit <branch> <message>");
		const git = (args) => execFileSync("git", [...args], { encoding: "utf8" });
		const oid = await createSignedCommit({
			api: apiFromEnv(),
			git,
			branch,
			message,
			changes: collectChanges({ git })
		});
		console.log(`created signed commit ${oid}`);
	}
};

//#endregion
//#region src/commands/index.ts
const commands = {
	"contract-version": contractVersion,
	"github-releases": githubReleases,
	"npm-publishing-mode": npmPublishingMode,
	"release-pr-body": releasePrBody,
	"shared-workflows-release": sharedWorkflowsRelease,
	"signed-commit": signedCommit
};
const usage = () => [
	"usage: gha.mjs <command> [args]",
	"",
	...Object.entries(commands).map(([name, command]) => `  ${name} ${command.usage}`)
].join("\n");

//#endregion
//#region src/cli.ts
const [name, ...argv] = process.argv.slice(2);
const command = name === void 0 ? void 0 : commands[name];
if (!command) {
	console.error(usage());
	process.exit(1);
}
try {
	await command.run(argv);
} catch (error) {
	console.error(error);
	process.exitCode = 1;
}

//#endregion
export {  };