// Generated by `pnpm --filter @zemd/gha run sync` from internal/gha/src. Do not edit.
import { closeSync, constants, existsSync, fstatSync, lstatSync, openSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from "node:path";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";

//#region src/semver.ts
const SEMVER = /^\d+\.\d+\.\d+$/;
const isReleaseVersion = (version) => SEMVER.test(version);
const parseVersion = (version) => {
	const [core = "", ...prerelease] = version.split("-");
	const [major = 0, minor = 0, patch = 0] = core.split(".").map(Number);
	return {
		major,
		minor,
		patch,
		prerelease: prerelease.join("-")
	};
};
const bumpType = (from, to) => {
	const a = parseVersion(from);
	const b = parseVersion(to);
	if (b.prerelease || a.prerelease) return "prerelease";
	if (b.major !== a.major) return "major";
	if (b.minor !== a.minor) return "minor";
	return "patch";
};

//#endregion
//#region src/contract-version.ts
const BUMP_PRIORITY = {
	patch: 0,
	minor: 1,
	major: 2
};
const scalar = (value) => {
	const trimmed = value.trim();
	const quote = trimmed.at(0);
	if ((quote === "\"" || quote === "'") && trimmed.at(-1) === quote) return trimmed.slice(1, -1);
	return trimmed;
};
const frontmatter = (source) => {
	return source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)?.[1] ?? "";
};
const packageBump = (source, packageName) => {
	for (const line of frontmatter(source).split(/\r?\n/)) {
		const separator = line.indexOf(":");
		if (separator < 0 || scalar(line.slice(0, separator)) !== packageName) continue;
		const bump = scalar(line.slice(separator + 1));
		if (bump === "major" || bump === "minor" || bump === "patch") return bump;
	}
};
const bumpContractVersion = (version, bump) => {
	if (!isReleaseVersion(version)) throw new Error(`contract version must be plain semver, got "${version}"`);
	const parsed = parseVersion(version);
	if (bump === "major") return `${parsed.major + 1}.0.0`;
	if (bump === "minor") return `${parsed.major}.${parsed.minor + 1}.0`;
	return `${parsed.major}.${parsed.minor}.${parsed.patch + 1}`;
};
const planContractVersion = (manifest, intents) => {
	const releases = intents.flatMap((intent) => {
		const bump = packageBump(intent.source, manifest.name);
		return bump === void 0 ? [] : [{
			id: intent.id,
			bump
		}];
	});
	if (releases.length === 0) return void 0;
	const bump = releases.reduce((highest, release) => BUMP_PRIORITY[release.bump] > BUMP_PRIORITY[highest] ? release.bump : highest, releases[0]?.bump ?? "patch");
	return {
		name: manifest.name,
		currentVersion: manifest.version,
		newVersion: bumpContractVersion(manifest.version, bump),
		bump,
		intentIds: releases.map(({ id }) => id).sort()
	};
};
const reconcileContractRelease = (releases, plan) => {
	const matching = releases.filter(({ name }) => name === plan.name);
	if (matching.length !== 1) throw new Error(`pnpm version reported ${matching.length} releases for ${plan.name}; expected exactly one`);
	const release = matching[0];
	if (!release) throw new Error(`pnpm version did not report ${plan.name}`);
	if (release.currentVersion === plan.currentVersion && release.newVersion === plan.newVersion) return releases;
	if (release.currentVersion !== plan.newVersion || release.newVersion !== plan.newVersion) throw new Error(`pnpm version reported an unexpected ${plan.name} transition: ${release.currentVersion} -> ${release.newVersion}; expected ${plan.newVersion} -> ${plan.newVersion}`);
	return releases.map((entry) => entry === release ? {
		...entry,
		currentVersion: plan.currentVersion
	} : entry);
};

//#endregion
//#region src/pnpm.ts
const asArray = (value, context) => {
	if (!Array.isArray(value)) throw new Error(`${context}: expected an array, got ${typeof value}`);
	return value;
};
const asRecord = (value, context) => {
	if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${context}: expected an object, got ${JSON.stringify(value)}`);
	return value;
};
const asString = (source, key, context) => {
	const value = source[key];
	if (typeof value !== "string") throw new Error(`${context}: expected "${key}" to be a string, got ${JSON.stringify(value)}`);
	return value;
};
const isPublicWorkspacePackage = (workspacePackage) => !workspacePackage.private;
const parseAppliedReleases = (json) => asArray(JSON.parse(json), "pnpm version -r --json").map((entry, index) => {
	const context = `pnpm version -r --json[${index}]`;
	const record = asRecord(entry, context);
	return {
		name: asString(record, "name", context),
		currentVersion: asString(record, "currentVersion", context),
		newVersion: asString(record, "newVersion", context)
	};
});
const parseWorkspacePackages = (json) => asArray(JSON.parse(json), "pnpm list -r --json").map((entry, index) => {
	const context = `pnpm list -r --json[${index}]`;
	const record = asRecord(entry, context);
	const name = asString(record, "name", context);
	const path = asString(record, "path", context);
	const isPrivate = record["private"] === true;
	if (record["version"] === void 0 && isPrivate) return {
		name,
		path,
		private: true
	};
	return {
		name,
		version: asString(record, "version", context),
		path,
		private: isPrivate
	};
});
const parsePublishSummary = (json) => {
	const published = asRecord(JSON.parse(json), "pnpm publish --report-summary")["publishedPackages"];
	if (published === void 0) return [];
	return asArray(published, "pnpm publish --report-summary.publishedPackages").map((entry, index) => {
		const context = `pnpm publish --report-summary.publishedPackages[${index}]`;
		const record = asRecord(entry, context);
		return {
			name: asString(record, "name", context),
			version: asString(record, "version", context)
		};
	});
};

//#endregion
//#region src/commands/contract-version.ts
const parseManifest$1 = (source, path) => {
	const value = JSON.parse(source);
	if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${path}: expected a package manifest object`);
	const manifest = value;
	if (typeof manifest["name"] !== "string" || typeof manifest["version"] !== "string") throw new Error(`${path}: expected string name and version fields`);
	if (manifest["private"] !== true) throw new Error(`${path}: contract version preparation is restricted to private packages`);
	return {
		name: manifest["name"],
		version: manifest["version"],
		private: true
	};
};
const replaceManifestVersion = (source, currentVersion, newVersion, path) => {
	const property = /("version"\s*:\s*")([^"]*)(")/g;
	const matches = [...source.matchAll(property)];
	if (matches.length !== 1 || matches[0]?.[2] !== currentVersion) throw new Error(`${path}: could not replace the unique version field`);
	return source.replace(property, `$1${newVersion}$3`);
};
const readIntents = (directory) => readdirSync(directory).filter((file) => file.endsWith(".md") && file.toLowerCase() !== "readme.md").sort().map((file) => ({
	id: basename(file, ".md"),
	source: readFileSync(join(directory, file), "utf8")
}));
const parsePlan = (source, path) => {
	const value = JSON.parse(source);
	if (value === null) return void 0;
	if (typeof value !== "object" || Array.isArray(value)) throw new Error(`${path}: expected a contract version plan or null`);
	const plan = value;
	const bump = plan["bump"];
	if (typeof plan["name"] !== "string" || typeof plan["currentVersion"] !== "string" || typeof plan["newVersion"] !== "string" || bump !== "major" && bump !== "minor" && bump !== "patch" || !Array.isArray(plan["intentIds"]) || !plan["intentIds"].every((id) => typeof id === "string")) throw new Error(`${path}: invalid contract version plan`);
	return {
		name: plan["name"],
		currentVersion: plan["currentVersion"],
		newVersion: plan["newVersion"],
		bump,
		intentIds: plan["intentIds"]
	};
};
const prepare$1 = (packagePath, intentsDirectory, statePath) => {
	const manifestSource = readFileSync(packagePath, "utf8");
	const manifest = parseManifest$1(manifestSource, packagePath);
	const plan = planContractVersion(manifest, readIntents(intentsDirectory));
	writeFileSync(statePath, `${JSON.stringify(plan ?? null, void 0, 2)}\n`);
	if (!plan) return;
	writeFileSync(packagePath, replaceManifestVersion(manifestSource, plan.currentVersion, plan.newVersion, packagePath));
};
const finalize = (statePath, releasesPath) => {
	const plan = parsePlan(readFileSync(statePath, "utf8"), statePath);
	if (!plan) return;
	const releases = parseAppliedReleases(readFileSync(releasesPath, "utf8"));
	writeFileSync(releasesPath, `${JSON.stringify(reconcileContractRelease(releases, plan), void 0, 2)}\n`);
};
const contractVersion = {
	usage: "prepare <package.json> <intents-dir> <state.json> | finalize <state.json> <releases.json>",
	run: (argv) => {
		const [operation, firstPath, secondPath, thirdPath] = argv;
		if (operation === "prepare" && firstPath && secondPath && thirdPath) {
			prepare$1(firstPath, secondPath, thirdPath);
			return;
		}
		if (operation === "finalize" && firstPath && secondPath && !thirdPath) {
			finalize(firstPath, secondPath);
			return;
		}
		throw new Error("usage: contract-version prepare <package.json> <intents-dir> <state.json> | finalize <state.json> <releases.json>");
	}
};

//#endregion
//#region src/env.ts
const requireEnv = (name) => {
	const value = process.env[name];
	if (!value) throw new Error(`${name} must be set`);
	return value;
};
const optionalEnv = (name, fallback) => {
	const value = process.env[name];
	return value ? value : fallback;
};

//#endregion
//#region src/release-tags.ts
const packageReleaseTag = (name, version) => `${name}@${version}`;

//#endregion
//#region src/github-releases.ts
const RELEASE_TAG_PREFIX = "release-";
const appendPackageTable = (out, heading, packages, approvalRequired) => {
	if (packages.length === 0) return;
	out.push(`## ${heading}`);
	if (approvalRequired) {
		out.push("");
		out.push("These versions require maintainer approval with 2FA before they become available from npm.");
		out.push("Rejecting one does not roll back this release or make its version reusable; release changes under a new version instead.");
	}
	out.push("");
	out.push("| Package | Version |");
	out.push("| :--- | ---: |");
	for (const { name, version } of packages) out.push(`| [\`${name}\`](https://www.npmjs.com/package/${name}) | \`${version}\` |`);
	out.push("");
};
const renderCombinedReleaseBody = ({ published, staged = [], changelogs, notes }) => {
	const out = [];
	const submitted = [...published, ...staged];
	appendPackageTable(out, "Published packages", published, false);
	appendPackageTable(out, "Packages staged on npm", staged, true);
	out.push("### Changelogs");
	out.push("");
	for (const { name, version } of submitted) {
		out.push("<details>");
		out.push(`<summary><code>${name}@${version}</code></summary>`);
		out.push("");
		out.push("<br>");
		out.push("");
		out.push(changelogs.get(name) || "_No changelog entry recorded._");
		out.push("");
		out.push("</details>");
		out.push("");
	}
	if (notes?.trim()) {
		out.push("---");
		out.push("");
		out.push(notes.trim());
	}
	return out.join("\n").trim();
};
const nextReleaseTag = async (api, now) => {
	const stamp = now.toISOString().slice(0, 16).replace("T", "-").replace(":", "");
	const base = `${RELEASE_TAG_PREFIX}${stamp}`;
	for (let counter = 1; counter < 100; counter += 1) {
		const tag = counter === 1 ? base : `${base}.${counter}`;
		if (!await api.tagExists(tag)) return tag;
	}
	throw new Error(`could not find a free release tag for ${base}`);
};
const previousReleaseTag = async (api) => {
	return (await api.listReleases()).filter((release) => release.tag_name.startsWith(RELEASE_TAG_PREFIX)).sort((a, b) => b.created_at.localeCompare(a.created_at))[0]?.tag_name ?? "";
};
const createTag = async (api, tag, sha) => {
	const response = await api.createRef(`refs/tags/${tag}`, sha);
	if (response.ok) {
		console.log(`created tag ${tag}`);
		return true;
	}
	if (response.status === 422 && await api.tagExists(tag)) {
		console.log(`tag ${tag} already exists, skipping`);
		return true;
	}
	console.error(`failed to create tag ${tag}:`, response.payload);
	return false;
};
const releasePublishedPackages = async ({ api, sha, published, staged = [], manifest, now = /* @__PURE__ */ new Date() }) => {
	if (published.length === 0 && staged.length === 0) {
		console.log("no packages were submitted to npm, nothing to release");
		return;
	}
	const publishedReleases = [...published].sort((a, b) => a.name.localeCompare(b.name));
	const stagedReleases = [...staged].sort((a, b) => a.name.localeCompare(b.name));
	const releases = [...publishedReleases, ...stagedReleases].sort((a, b) => a.name.localeCompare(b.name));
	const packages = new Map(manifest.packages.map((entry) => [entry.name, entry]));
	const submitted = /* @__PURE__ */ new Set();
	for (const release of releases) {
		if (submitted.has(release.name)) throw new Error(`package was submitted more than once: ${release.name}`);
		submitted.add(release.name);
		const artifact = packages.get(release.name);
		if (!artifact || artifact.version !== release.version) throw new Error(`submitted package is absent from the validated artifact: ${release.name}@${release.version}`);
	}
	const changelogs = new Map(manifest.packages.map((entry) => [entry.name, entry.changelog]));
	let failed = false;
	for (const { name, version } of releases) if (!await createTag(api, packageReleaseTag(name, version), sha)) failed = true;
	const releaseTag = await nextReleaseTag(api, now);
	const notes = await api.generateNotes(releaseTag, sha, await previousReleaseTag(api));
	const created = await api.createRelease({
		tag: releaseTag,
		name: releaseTag,
		targetCommitish: sha,
		body: renderCombinedReleaseBody({
			published: publishedReleases,
			staged: stagedReleases,
			changelogs,
			notes
		}),
		prerelease: releases.every(({ version }) => version.includes("-"))
	});
	if (created.ok) console.log(`created release ${releaseTag}`);
	else {
		failed = true;
		console.error(`failed to create release ${releaseTag}:`, created.payload);
	}
	if (failed) throw new Error("one or more release steps failed");
};

//#endregion
//#region src/changelog.ts
const MAX_CHANGELOG_BYTES$1 = 1048576;
const isWithin$2 = (root, path) => {
	const fromRoot = relative(root, path);
	return fromRoot === "" || !isAbsolute(fromRoot) && fromRoot !== ".." && !fromRoot.startsWith(`..${sep}`);
};
const changelogEntry = (packagePath, version) => {
	let changelog;
	try {
		const root = realpathSync(resolve(packagePath));
		const path = join(root, "CHANGELOG.md");
		const metadata = lstatSync(path);
		if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size > MAX_CHANGELOG_BYTES$1) return "";
		const canonical = realpathSync(path);
		if (!isWithin$2(root, canonical)) return "";
		changelog = readFileSync(canonical, "utf8");
	} catch {
		return "";
	}
	const lines = changelog.split("\n");
	const start = lines.findIndex((line) => line.trim().replace(/\s+-\s+\d{4}-\d{2}-\d{2}$/, "").replace(/[[\]]/g, "") === `## ${version}`);
	if (start === -1) return "";
	const rest = lines.slice(start + 1);
	const end = rest.findIndex((line) => line.startsWith("## "));
	return (end === -1 ? rest : rest.slice(0, end)).join("\n").replace(/^#{1,6}\s+(.+)$/gm, "**$1**").trim();
};

//#endregion
//#region src/package-artifact.ts
const MAX_PACKAGES$1 = 100;
const MAX_TARBALL_BYTES = 52428800;
const MAX_TOTAL_BYTES = 524288e3;
const MAX_CHANGELOG_BYTES = 1048576;
const NPM_REGISTRY = "https://registry.npmjs.org";
const PACKAGE_NAME$1 = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
const PACKAGE_VERSION$1 = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const TARBALL_NAME = /^package-\d{4}\.tgz$/;
const isWithin$1 = (root, path) => {
	const fromRoot = relative(root, path);
	return fromRoot === "" || !isAbsolute(fromRoot) && fromRoot !== ".." && !fromRoot.startsWith(`..${sep}`);
};
const record$2 = (value, context) => {
	if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`${context}: expected an object`);
	return value;
};
const exactKeys$2 = (value, expected, context) => {
	if (Object.keys(value).sort().join("\0") !== [...expected].sort().join("\0")) throw new Error(`${context}: expected only ${expected.join(", ")}`);
};
const stringField$1 = (value, key, context) => {
	const field = value[key];
	if (typeof field !== "string") throw new Error(`${context}.${key}: expected a string`);
	return field;
};
const portablePath = (path) => {
	if (path === ".") return path;
	if (path.length === 0 || path.length > 4096 || path.includes("\\") || isAbsolute(path) || path.startsWith("../") || path.split("/").some((segment) => segment === "" || segment === "." || segment === "..")) throw new Error(`invalid workspace path: ${JSON.stringify(path)}`);
	return path;
};
const validateNameVersion$1 = (name, version) => {
	if (name.length > 214 || !PACKAGE_NAME$1.test(name)) throw new Error(`invalid npm package name: ${JSON.stringify(name)}`);
	if (!PACKAGE_VERSION$1.test(version)) throw new Error(`invalid npm package version: ${JSON.stringify(version)}`);
};
const regularTarball = (directory, file) => {
	if (!TARBALL_NAME.test(file)) throw new Error(`invalid release tarball name: ${file}`);
	const path = resolve(directory, file);
	if (!isWithin$1(directory, path)) throw new Error(`release tarball is outside its artifact: ${file}`);
	const metadata = lstatSync(path);
	if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size === 0 || metadata.size > MAX_TARBALL_BYTES) throw new Error(`${file} must be a non-empty regular file of at most ${MAX_TARBALL_BYTES} bytes`);
	if (realpathSync(path) !== path) throw new Error(`${file} must not traverse a symbolic link`);
	return {
		path,
		size: metadata.size
	};
};
const hash = (path) => {
	return createHash("sha256").update(readFileSync(path)).digest("hex");
};
const artifactDirectory$2 = (path) => {
	const absolute = realpathSync(resolve(path));
	const metadata = lstatSync(resolve(path));
	if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error(`${path} must be a regular directory`);
	return absolute;
};
const defaultPack = (packagePath, outputPath) => {
	execFileSync("pnpm", [
		"--dir",
		packagePath,
		"pack",
		"--out",
		outputPath
	], { stdio: "inherit" });
};
const defaultInspect = (tarballPath) => {
	const source = execFileSync("pnpm", [
		"publish",
		tarballPath,
		"--dry-run",
		"--json",
		"--ignore-scripts",
		"--no-git-checks",
		"--registry",
		NPM_REGISTRY
	], { encoding: "utf8" });
	const value = record$2(JSON.parse(source), `dry-run metadata for ${tarballPath}`);
	return {
		name: stringField$1(value, "name", `dry-run metadata for ${tarballPath}`),
		version: stringField$1(value, "version", `dry-run metadata for ${tarballPath}`)
	};
};
const parseManifest = (source) => {
	const value = record$2(JSON.parse(source), "package artifact manifest");
	exactKeys$2(value, ["packages"], "package artifact manifest");
	if (!Array.isArray(value["packages"]) || value["packages"].length > MAX_PACKAGES$1) throw new Error(`package artifact manifest must contain at most ${MAX_PACKAGES$1} packages`);
	const names = /* @__PURE__ */ new Set();
	const files = /* @__PURE__ */ new Set();
	return { packages: value["packages"].map((entry, index) => {
		const context = `package artifact manifest.packages[${index}]`;
		const item = record$2(entry, context);
		exactKeys$2(item, [
			"changelog",
			"file",
			"name",
			"path",
			"sha256",
			"version"
		], context);
		const result = {
			changelog: stringField$1(item, "changelog", context),
			file: stringField$1(item, "file", context),
			name: stringField$1(item, "name", context),
			path: portablePath(stringField$1(item, "path", context)),
			sha256: stringField$1(item, "sha256", context),
			version: stringField$1(item, "version", context)
		};
		validateNameVersion$1(result.name, result.version);
		if (!TARBALL_NAME.test(result.file) || !/^[a-f0-9]{64}$/.test(result.sha256)) throw new Error(`${context}: invalid tarball filename or SHA-256 digest`);
		if (Buffer.byteLength(result.changelog) > MAX_CHANGELOG_BYTES) throw new Error(`${context}: changelog is too large`);
		if (names.has(result.name) || files.has(result.file)) throw new Error(`${context}: duplicate package name or tarball`);
		names.add(result.name);
		files.add(result.file);
		return result;
	}) };
};
const createPackageArtifact = ({ directory: inputDirectory, pack = defaultPack, root = process.cwd(), workspace }) => {
	const directory = artifactDirectory$2(inputDirectory);
	if (readdirSync(directory).length !== 0) throw new Error("package artifact directory is not empty");
	const canonicalRoot = realpathSync(resolve(root));
	const publicPackages = workspace.filter(isPublicWorkspacePackage);
	if (publicPackages.length === 0 || publicPackages.length > MAX_PACKAGES$1) throw new Error(`expected between 1 and ${MAX_PACKAGES$1} public packages`);
	const manifest = { packages: publicPackages.map((workspacePackage, index) => {
		validateNameVersion$1(workspacePackage.name, workspacePackage.version);
		const sourcePackagePath = resolve(canonicalRoot, workspacePackage.path);
		const packagePath = realpathSync(sourcePackagePath);
		if (!isWithin$1(canonicalRoot, packagePath)) throw new Error(`workspace package is outside the repository: ${workspacePackage.path}`);
		const packageMetadata = lstatSync(sourcePackagePath);
		if (!packageMetadata.isDirectory() || packageMetadata.isSymbolicLink()) throw new Error(`workspace package is not a regular directory: ${workspacePackage.path}`);
		const file = `package-${String(index).padStart(4, "0")}.tgz`;
		const outputPath = resolve(directory, file);
		pack(packagePath, outputPath);
		regularTarball(directory, file);
		return {
			changelog: changelogEntry(packagePath, workspacePackage.version),
			file,
			name: workspacePackage.name,
			path: portablePath(relative(canonicalRoot, packagePath).split(sep).join("/")),
			sha256: hash(outputPath),
			version: workspacePackage.version
		};
	}) };
	writeFileSync(resolve(directory, "manifest.json"), `${JSON.stringify(manifest)}\n`, {
		encoding: "utf8",
		flag: "wx",
		mode: 384
	});
	return manifest;
};
const validatePackageArtifact = ({ directory: inputDirectory, inspect = defaultInspect }) => {
	const directory = artifactDirectory$2(inputDirectory);
	const entries = readdirSync(directory).sort();
	const manifestPath = resolve(directory, "manifest.json");
	const manifestMetadata = lstatSync(manifestPath);
	if (!manifestMetadata.isFile() || manifestMetadata.isSymbolicLink() || manifestMetadata.size > MAX_CHANGELOG_BYTES) throw new Error("manifest.json must be a regular file of at most 1 MiB");
	const manifest = parseManifest(readFileSync(manifestPath, "utf8"));
	const expected = ["manifest.json", ...manifest.packages.map(({ file }) => file)].sort();
	if (entries.join("\0") !== expected.join("\0")) throw new Error("package artifact contains unexpected or missing files");
	let totalBytes = 0;
	for (const packageEntry of manifest.packages) {
		const tarball = regularTarball(directory, packageEntry.file);
		totalBytes += tarball.size;
		if (totalBytes > MAX_TOTAL_BYTES) throw new Error(`package artifact exceeds ${MAX_TOTAL_BYTES} bytes`);
		if (hash(tarball.path) !== packageEntry.sha256) throw new Error(`SHA-256 mismatch for ${packageEntry.file}`);
		const inspected = inspect(tarball.path);
		if (inspected.name !== packageEntry.name || inspected.version !== packageEntry.version) throw new Error(`package metadata mismatch for ${packageEntry.file}`);
	}
	return manifest;
};
const workspaceFromPackageArtifact = (manifest) => {
	return manifest.packages.map(({ name, path, version }) => ({
		name,
		path,
		private: false,
		version
	}));
};
const tarballForPackage = (directory, manifest, packageName) => {
	const entry = manifest.packages.find(({ name }) => name === packageName);
	if (!entry) throw new Error(`package is absent from the release artifact: ${packageName}`);
	const artifact = artifactDirectory$2(directory);
	const tarball = regularTarball(artifact, entry.file);
	if (hash(tarball.path) !== entry.sha256) throw new Error(`SHA-256 mismatch for ${entry.file}`);
	return tarball.path;
};
const publishSummary = (manifest, packageNames) => {
	if (new Set(packageNames).size !== packageNames.length) throw new Error("publish summary contains duplicates");
	return { publishedPackages: packageNames.map((packageName) => {
		const entry = manifest.packages.find(({ name }) => name === packageName);
		if (!entry) throw new Error(`package is absent from the release artifact: ${packageName}`);
		return {
			name: entry.name,
			version: entry.version
		};
	}) };
};
const parsePackageArtifactManifest = (source) => {
	return parseManifest(source);
};

//#endregion
//#region src/github.ts
const COMMIT_MUTATION = `
    mutation ($input: CreateCommitOnBranchInput!) {
      createCommitOnBranch(input: $input) {
        commit {
          oid
        }
      }
    }
  `;
const createGitHubApi = (options) => {
	const { token, repository } = options;
	const apiUrl = options.apiUrl ?? "https://api.github.com";
	const graphqlUrl = options.graphqlUrl ?? "https://api.github.com/graphql";
	const doFetch = options.fetch ?? globalThis.fetch;
	const requestUrl = async (url, method, body) => {
		const response = await doFetch(url, {
			method,
			headers: {
				accept: "application/vnd.github+json",
				authorization: `Bearer ${token}`,
				"content-type": "application/json",
				"x-github-api-version": "2022-11-28"
			},
			...body === void 0 ? {} : { body: JSON.stringify(body) }
		});
		const text = await response.text();
		return {
			ok: response.ok,
			status: response.status,
			payload: text ? JSON.parse(text) : {}
		};
	};
	const request = (path, method, body) => requestUrl(`${apiUrl}${path}`, method, body);
	const api = {
		repository,
		request,
		graphql: (query, variables) => requestUrl(graphqlUrl, "POST", {
			query,
			variables
		}),
		tagExists: async (tag) => {
			const response = await request(`/repos/${repository}/git/ref/tags/${encodeURIComponent(tag)}`, "GET");
			if (response.status === 404) return false;
			if (!response.ok) throw new Error(`failed to check git tag "${tag}": GitHub returned ${response.status}`);
			return true;
		},
		releaseExists: async (tag) => {
			const response = await request(`/repos/${repository}/releases/tags/${encodeURIComponent(tag)}`, "GET");
			if (response.status === 404) return false;
			if (!response.ok) throw new Error(`failed to check GitHub release "${tag}": GitHub returned ${response.status}`);
			return true;
		},
		createRef: (ref, sha) => request(`/repos/${repository}/git/refs`, "POST", {
			ref,
			sha
		}),
		updateRef: (ref, sha) => request(`/repos/${repository}/git/${ref}`, "PATCH", {
			sha,
			force: true
		}),
		listReleases: async () => {
			const response = await request(`/repos/${repository}/releases?per_page=100`, "GET");
			return response.ok ? response.payload : [];
		},
		generateNotes: async (tag, sha, previousTag) => {
			const response = await request(`/repos/${repository}/releases/generate-notes`, "POST", {
				tag_name: tag,
				target_commitish: sha,
				...previousTag ? { previous_tag_name: previousTag } : {}
			});
			if (!response.ok) {
				console.warn(`failed to generate notes for ${tag}:`, response.payload);
				return "";
			}
			return (response.payload.body ?? "").trim();
		},
		createRelease: (release) => request(`/repos/${repository}/releases`, "POST", {
			tag_name: release.tag,
			name: release.name,
			body: release.body,
			draft: false,
			prerelease: release.prerelease,
			...release.targetCommitish === void 0 ? {} : { target_commitish: release.targetCommitish }
		}),
		createCommitOnBranch: async (branch, expectedHeadOid, message, fileChanges) => {
			const [headline, ...body] = message.split("\n\n");
			const rest = body.join("\n\n");
			const result = await api.graphql(COMMIT_MUTATION, { input: {
				branch: {
					repositoryNameWithOwner: repository,
					branchName: branch
				},
				expectedHeadOid,
				message: {
					headline,
					...rest ? { body: rest } : {}
				},
				fileChanges
			} });
			const oid = result.payload.data?.createCommitOnBranch.commit.oid;
			if (!result.ok || result.payload.errors || !oid) throw new Error(`failed to create commit: ${JSON.stringify(result.payload.errors ?? result.payload)}`);
			return oid;
		}
	};
	return api;
};

//#endregion
//#region src/commands/context.ts
const apiFromEnv = () => createGitHubApi({
	token: requireEnv("GITHUB_TOKEN"),
	repository: requireEnv("GITHUB_REPOSITORY"),
	apiUrl: optionalEnv("GITHUB_API_URL", "https://api.github.com"),
	graphqlUrl: optionalEnv("GITHUB_GRAPHQL_URL", "https://api.github.com/graphql")
});

//#endregion
//#region src/commands/github-releases.ts
const readSummary = (path) => existsSync(path) ? parsePublishSummary(readFileSync(path, "utf8")) : [];
const githubReleases = {
	usage: "<published-summary.json> <staged-summary.json> <release-manifest.json>",
	run: async (argv) => {
		const [publishedSummaryPath, stagedSummaryPath, manifestPath] = argv;
		if (!publishedSummaryPath || !stagedSummaryPath || !manifestPath) throw new Error("usage: github-releases <published-summary.json> <staged-summary.json> <release-manifest.json>");
		await releasePublishedPackages({
			api: apiFromEnv(),
			sha: requireEnv("GITHUB_SHA"),
			published: readSummary(publishedSummaryPath),
			staged: readSummary(stagedSummaryPath),
			manifest: parsePackageArtifactManifest(readFileSync(manifestPath, "utf8"))
		});
	}
};

//#endregion
//#region src/npm-publishing.ts
const packageUrl = (registryUrl, packageName) => {
	const registry = new URL(registryUrl);
	if (!registry.pathname.endsWith("/")) registry.pathname += "/";
	const encodedName = encodeURIComponent(packageName).replace(/^%40/, "@");
	return new URL(encodedName, registry);
};
const packageExistsOnRegistry = async (packageName, registryUrl, request) => {
	const response = await request(packageUrl(registryUrl, packageName), { headers: { accept: "application/vnd.npm.install-v1+json" } });
	if (response.status === 404) return false;
	if (!response.ok) {
		const status = response.statusText ? `${response.status} ${response.statusText}` : String(response.status);
		throw new Error(`npm registry lookup for "${packageName}" failed: ${status}`);
	}
	return true;
};
const planNpmPublishing = async (workspace, stagedPublishing, packageExists, releaseTagExists) => {
	const publicPackages = workspace.filter(isPublicWorkspacePackage);
	const submissionState = await Promise.all(publicPackages.map(async (workspacePackage) => ({
		workspacePackage,
		submitted: await releaseTagExists(packageReleaseTag(workspacePackage.name, workspacePackage.version))
	})));
	const previouslySubmittedPackages = submissionState.filter(({ submitted }) => submitted).map(({ workspacePackage: { name, version } }) => ({
		name,
		version
	}));
	const pendingPackages = submissionState.filter(({ submitted }) => !submitted).map(({ workspacePackage }) => workspacePackage);
	const existence = await Promise.all(pendingPackages.map(async (workspacePackage) => ({
		name: workspacePackage.name,
		exists: await packageExists(workspacePackage.name)
	})));
	const firstReleasePackages = existence.filter(({ exists }) => !exists).map(({ name }) => name);
	const directPackages = stagedPublishing ? firstReleasePackages : existence.map(({ name }) => name);
	const stagedPackages = stagedPublishing ? existence.filter(({ exists }) => exists).map(({ name }) => name) : [];
	let mode;
	if (directPackages.length > 0) mode = stagedPackages.length > 0 ? "mixed" : "direct";
	else if (stagedPackages.length > 0) mode = "staged";
	else mode = "none";
	return {
		mode,
		directPackages,
		firstReleasePackages,
		previouslySubmittedPackages,
		stagedPackages
	};
};

//#endregion
//#region src/commands/npm-publishing-mode.ts
const parseBoolean = (value) => {
	if (value === "true") return true;
	if (value === "false") return false;
	throw new Error(`npm-publishing-mode: expected "true" or "false", got "${value}"`);
};
const npmPublishingMode = {
	usage: "<workspace-list.json> <registry-url> <staged-publishing> <first-releases.txt> <direct-packages.txt> <staged-packages.txt>",
	run: async (argv) => {
		const [workspacePath, registryUrl, rawStagedPublishing, firstReleasesPath, directPackagesPath, stagedPackagesPath] = argv;
		if (!workspacePath || !registryUrl || !rawStagedPublishing || !firstReleasesPath || !directPackagesPath || !stagedPackagesPath) throw new Error("usage: npm-publishing-mode <workspace-list.json> <registry-url> <staged-publishing> <first-releases.txt> <direct-packages.txt> <staged-packages.txt>");
		const stagedPublishing = parseBoolean(rawStagedPublishing);
		const api = apiFromEnv();
		const plan = await planNpmPublishing(parseWorkspacePackages(readFileSync(workspacePath, "utf8")), stagedPublishing, (packageName) => packageExistsOnRegistry(packageName, registryUrl, (url, init) => fetch(url, { headers: init.headers })), (tag) => api.tagExists(tag));
		if (plan.previouslySubmittedPackages.length > 0) console.error(`Skipping versions already recorded by immutable release tags: ${plan.previouslySubmittedPackages.map(({ name, version }) => packageReleaseTag(name, version)).join(", ")}`);
		if (plan.firstReleasePackages.length > 0) console.error(`Regular npm publishing is required for first release: ${plan.firstReleasePackages.join(", ")}`);
		writeFileSync(firstReleasesPath, plan.firstReleasePackages.map((packageName) => `${packageName}\n`).join(""));
		writeFileSync(directPackagesPath, plan.directPackages.map((packageName) => `${packageName}\n`).join(""));
		writeFileSync(stagedPackagesPath, plan.stagedPackages.map((packageName) => `${packageName}\n`).join(""));
		process.stdout.write([
			`mode=${plan.mode}`,
			`pending=${plan.mode !== "none"}`,
			`direct=${plan.directPackages.length > 0}`,
			`stage=${plan.stagedPackages.length > 0}`,
			`first_release=${plan.firstReleasePackages.length > 0}`,
			""
		].join("\n"));
	}
};

//#endregion
//#region src/commands/package-artifact.ts
const writeExclusiveJson = (path, value) => {
	writeFileSync(path, `${JSON.stringify(value)}\n`, {
		encoding: "utf8",
		flag: "wx",
		mode: 384
	});
};
const packageNames = (path) => {
	return readFileSync(path, "utf8").split("\n").filter(Boolean);
};
const packageArtifact = {
	usage: "<create|validate|tarball|summary> ...",
	run: (argv) => {
		const [operation, ...args] = argv;
		if (operation === "create") {
			const [workspacePath, directory] = args;
			if (!workspacePath || !directory) throw new Error("usage: package-artifact create <workspace-list.json> <artifact-directory>");
			createPackageArtifact({
				directory,
				workspace: parseWorkspacePackages(readFileSync(workspacePath, "utf8"))
			});
			return;
		}
		if (operation === "validate") {
			const [directory, manifestPath, workspacePath] = args;
			if (!directory || !manifestPath || !workspacePath) throw new Error("usage: package-artifact validate <artifact-directory> <manifest.json> <workspace-list.json>");
			const manifest = validatePackageArtifact({ directory });
			writeExclusiveJson(manifestPath, manifest);
			writeExclusiveJson(workspacePath, workspaceFromPackageArtifact(manifest));
			return;
		}
		if (operation === "tarball") {
			const [manifestPath, directory, packageName] = args;
			if (!manifestPath || !directory || !packageName) throw new Error("usage: package-artifact tarball <manifest.json> <artifact-directory> <package-name>");
			const manifest = parsePackageArtifactManifest(readFileSync(manifestPath, "utf8"));
			process.stdout.write(`${tarballForPackage(directory, manifest, packageName)}\n`);
			return;
		}
		if (operation === "summary") {
			const [manifestPath, packageNamesPath, outputPath] = args;
			if (!manifestPath || !packageNamesPath || !outputPath) throw new Error("usage: package-artifact summary <manifest.json> <package-names.txt> <summary.json>");
			const manifest = parsePackageArtifactManifest(readFileSync(manifestPath, "utf8"));
			writeExclusiveJson(outputPath, publishSummary(manifest, packageNames(packageNamesPath)));
			return;
		}
		throw new Error("usage: package-artifact <create|validate|tarball|summary> ...");
	}
};

//#endregion
//#region src/signed-commit.ts
const MAX_RELEASE_FILES = 1e3;
const MAX_RELEASE_FILE_BYTES = 10485760;
const MAX_RELEASE_TOTAL_BYTES = 52428800;
const MAX_REPOSITORY_PATH_BYTES = 4096;
const isWithin = (root, path) => {
	const fromRoot = relative(root, path);
	return fromRoot === "" || !isAbsolute(fromRoot) && fromRoot !== ".." && !fromRoot.startsWith(`..${sep}`);
};
const repositoryPath = (path) => {
	if (path.length === 0 || Buffer.byteLength(path) > MAX_REPOSITORY_PATH_BYTES || path.includes("\\") || isAbsolute(path) || posix.normalize(path) !== path || path === "." || path.startsWith("../")) throw new Error(`unsafe release path: ${JSON.stringify(path)}`);
	return path;
};
const workspaceReleasePaths = (root, sourceRoot, workspacePaths) => {
	const allowed = /* @__PURE__ */ new Set(["pnpm-lock.yaml", ".changeset/ledger.yaml"]);
	for (const workspacePath of workspacePaths) {
		const absolute = resolve(workspacePath);
		if (!isWithin(sourceRoot, absolute)) throw new Error(`workspace path is outside the repository: ${workspacePath}`);
		const metadata = lstatSync(absolute);
		if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error(`workspace path is not a regular directory: ${workspacePath}`);
		const canonical = realpathSync(absolute);
		if (canonical !== resolve(root, relative(sourceRoot, absolute)) || !isWithin(root, canonical)) throw new Error(`workspace path traverses a symbolic link: ${workspacePath}`);
		const directory = relative(root, canonical).split(sep).join("/");
		allowed.add(directory ? `${directory}/package.json` : "package.json");
		allowed.add(directory ? `${directory}/CHANGELOG.md` : "CHANGELOG.md");
	}
	return allowed;
};
const isChangesetDeletion = (path) => {
	return /^\.changeset\/[a-z0-9]+(?:-[a-z0-9]+)*\.md$/.test(path);
};
const isPortablePackageMetadataPath = (path) => {
	if (path === "package.json" || path === "CHANGELOG.md") return true;
	const segments = path.split("/");
	const filename = segments.pop();
	return (filename === "package.json" || filename === "CHANGELOG.md") && segments.length > 0 && segments.every((segment) => segment !== "node_modules" && !segment.startsWith(".") && /^[A-Za-z0-9@_][A-Za-z0-9@._-]*$/.test(segment));
};
const isPortableReleaseAddition = (path) => {
	return path === "pnpm-lock.yaml" || path === ".changeset/ledger.yaml" || isPortablePackageMetadataPath(path);
};
const readRegularFile = (root, path) => {
	const absolute = resolve(root, repositoryPath(path));
	if (!isWithin(root, absolute)) throw new Error(`release path is outside the repository: ${path}`);
	const before = lstatSync(absolute);
	if (!before.isFile() || before.isSymbolicLink()) throw new Error(`release path is not a regular file: ${path}`);
	if (before.size > MAX_RELEASE_FILE_BYTES) throw new Error(`release file is larger than ${MAX_RELEASE_FILE_BYTES} bytes: ${path}`);
	const canonical = realpathSync(absolute);
	if (canonical !== absolute || !isWithin(root, canonical)) throw new Error(`release path traverses a symbolic link: ${path}`);
	const descriptor = openSync(absolute, constants.O_RDONLY | constants.O_NOFOLLOW);
	try {
		const opened = fstatSync(descriptor);
		if (!opened.isFile() || opened.dev !== before.dev || opened.ino !== before.ino) throw new Error(`release file changed while it was being opened: ${path}`);
		if (opened.size > MAX_RELEASE_FILE_BYTES) throw new Error(`release file is larger than ${MAX_RELEASE_FILE_BYTES} bytes: ${path}`);
		return readFileSync(descriptor);
	} finally {
		closeSync(descriptor);
	}
};
const changedPaths = (status) => {
	const additions = /* @__PURE__ */ new Set();
	const deletions = /* @__PURE__ */ new Set();
	for (const record of status.split("\0").filter(Boolean)) {
		if (record.length < 4 || record[2] !== " ") throw new Error(`invalid git status record: ${JSON.stringify(record)}`);
		const state = record.slice(0, 2);
		const path = repositoryPath(record.slice(3));
		if (state === " M" || state === "??") additions.add(path);
		else if (state === " D") deletions.add(path);
		else throw new Error(`unexpected git status ${JSON.stringify(state)} for ${path}`);
	}
	return {
		additions,
		deletions
	};
};
const collectChanges = ({ git, root = process.cwd(), workspacePaths }) => {
	const sourceRoot = resolve(root);
	const canonicalRoot = realpathSync(sourceRoot);
	const allowedAdditions = workspaceReleasePaths(canonicalRoot, sourceRoot, workspacePaths);
	const changed = changedPaths(git([
		"status",
		"--porcelain=v1",
		"-z",
		"--untracked-files=all"
	]));
	if (changed.additions.size + changed.deletions.size > MAX_RELEASE_FILES) throw new Error(`release contains more than ${MAX_RELEASE_FILES} files`);
	let totalBytes = 0;
	return {
		additions: [...changed.additions].map((path) => {
			if (!allowedAdditions.has(path)) throw new Error(`unexpected release addition: ${path}`);
			const contents = readRegularFile(canonicalRoot, path);
			totalBytes += contents.byteLength;
			if (totalBytes > MAX_RELEASE_TOTAL_BYTES) throw new Error(`release contents exceed ${MAX_RELEASE_TOTAL_BYTES} bytes`);
			return {
				path,
				contents: contents.toString("base64")
			};
		}),
		deletions: [...changed.deletions].map((path) => {
			if (!isChangesetDeletion(path)) throw new Error(`unexpected release deletion: ${path}`);
			return { path };
		})
	};
};
const record$1 = (value, context) => {
	if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`${context}: expected an object`);
	return value;
};
const exactKeys$1 = (value, expected, context) => {
	if (Object.keys(value).sort().join("\0") !== [...expected].sort().join("\0")) throw new Error(`${context}: expected only ${expected.join(", ")}`);
};
const parseFileChanges = (source) => {
	const value = record$1(JSON.parse(source), "release changes");
	exactKeys$1(value, ["additions", "deletions"], "release changes");
	if (!Array.isArray(value["additions"]) || !Array.isArray(value["deletions"])) throw new Error("release changes: additions and deletions must be arrays");
	if (value["additions"].length + value["deletions"].length > MAX_RELEASE_FILES) throw new Error(`release contains more than ${MAX_RELEASE_FILES} files`);
	const paths = /* @__PURE__ */ new Set();
	let totalBytes = 0;
	return {
		additions: value["additions"].map((entry, index) => {
			const item = record$1(entry, `release changes.additions[${index}]`);
			exactKeys$1(item, ["contents", "path"], `release changes.additions[${index}]`);
			if (typeof item["path"] !== "string" || typeof item["contents"] !== "string") throw new Error(`release changes.additions[${index}]: path and contents must be strings`);
			const path = repositoryPath(item["path"]);
			if (!isPortableReleaseAddition(path)) throw new Error(`unexpected release addition: ${path}`);
			if (paths.has(path)) throw new Error(`duplicate release path: ${path}`);
			paths.add(path);
			const contents = Buffer.from(item["contents"], "base64");
			if (contents.toString("base64") !== item["contents"]) throw new Error(`release changes.additions[${index}]: contents are not canonical base64`);
			if (contents.byteLength > MAX_RELEASE_FILE_BYTES) throw new Error(`release file is larger than ${MAX_RELEASE_FILE_BYTES} bytes: ${path}`);
			totalBytes += contents.byteLength;
			if (totalBytes > MAX_RELEASE_TOTAL_BYTES) throw new Error(`release contents exceed ${MAX_RELEASE_TOTAL_BYTES} bytes`);
			return {
				path,
				contents: item["contents"]
			};
		}),
		deletions: value["deletions"].map((entry, index) => {
			const item = record$1(entry, `release changes.deletions[${index}]`);
			exactKeys$1(item, ["path"], `release changes.deletions[${index}]`);
			if (typeof item["path"] !== "string") throw new Error(`release changes.deletions[${index}]: path must be a string`);
			const path = repositoryPath(item["path"]);
			if (!isChangesetDeletion(path)) throw new Error(`unexpected release deletion: ${path}`);
			if (paths.has(path)) throw new Error(`duplicate release path: ${path}`);
			paths.add(path);
			return { path };
		})
	};
};
const createSignedCommit = async ({ api, baseOid, branch, message, changes }) => {
	if (changes.additions.length === 0 && changes.deletions.length === 0) throw new Error("nothing to commit");
	if (!/^[0-9a-f]{40}$/i.test(baseOid)) throw new Error(`expected a 40-character commit SHA, got ${JSON.stringify(baseOid)}`);
	const ref = `refs/heads/${branch}`;
	if (!(await api.createRef(ref, baseOid)).ok) {
		const updated = await api.updateRef(ref, baseOid);
		if (!updated.ok) throw new Error(`failed to point ${branch} at ${baseOid}: ${JSON.stringify(updated.payload)}`);
	}
	return api.createCommitOnBranch(branch, baseOid, message, changes);
};

//#endregion
//#region src/release-pr-artifact.ts
const CHANGE_FILE = "changes.json";
const BODY_FILE = "pr-body.md";
const MAX_BODY_BYTES = 1048576;
const regularFile = (path, maxBytes) => {
	const absolute = resolve(path);
	const metadata = lstatSync(absolute);
	if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size > maxBytes) throw new Error(`${path} must be a regular file of at most ${maxBytes} bytes`);
	if (realpathSync(absolute) !== absolute) throw new Error(`${path} must not traverse a symbolic link`);
};
const artifactDirectory$1 = (path, expectedEntries) => {
	const absolute = resolve(path);
	const metadata = lstatSync(absolute);
	if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error(`${path} must be a regular directory`);
	if (readdirSync(absolute).sort().join("\0") !== [...expectedEntries].sort().join("\0")) throw new Error(`${path} must contain only ${expectedEntries.join(" and ")}`);
	return realpathSync(absolute);
};
const createReleasePrArtifact = ({ artifactDirectory: output, git, prBodyPath, root = process.cwd(), workspacePaths }) => {
	const directory = artifactDirectory$1(output, []);
	regularFile(prBodyPath, MAX_BODY_BYTES);
	const body = readFileSync(prBodyPath);
	const changes = collectChanges({
		git,
		root,
		workspacePaths
	});
	writeFileSync(resolve(directory, CHANGE_FILE), `${JSON.stringify(changes)}\n`, {
		encoding: "utf8",
		flag: "wx",
		mode: 384
	});
	writeFileSync(resolve(directory, BODY_FILE), body, {
		flag: "wx",
		mode: 384
	});
};
const readReleasePrArtifact = (path) => {
	const directory = artifactDirectory$1(path, [BODY_FILE, CHANGE_FILE]);
	const changesPath = resolve(directory, CHANGE_FILE);
	const bodyPath = resolve(directory, BODY_FILE);
	regularFile(changesPath, 73400320);
	regularFile(bodyPath, MAX_BODY_BYTES);
	return {
		bodyPath,
		changes: parseFileChanges(readFileSync(changesPath, "utf8"))
	};
};

//#endregion
//#region src/commands/release-pr-artifact.ts
const releasePrArtifact = {
	usage: "<workspace-list.json> <pr-body.md> <artifact-directory>",
	run: (argv) => {
		const [workspacePath, prBodyPath, artifactDirectory] = argv;
		if (!workspacePath || !prBodyPath || !artifactDirectory) throw new Error("usage: release-pr-artifact <workspace-list.json> <pr-body.md> <artifact-directory>");
		const workspace = parseWorkspacePackages(readFileSync(workspacePath, "utf8"));
		const git = (args) => execFileSync("git", [...args], {
			encoding: "utf8",
			maxBuffer: 16777216
		});
		createReleasePrArtifact({
			artifactDirectory,
			git,
			prBodyPath,
			workspacePaths: workspace.map(({ path }) => path)
		});
	}
};

//#endregion
//#region src/release-pr-body.ts
const badge = {
	major: "**major**",
	minor: "**minor**",
	patch: "patch",
	prerelease: "prerelease",
	new: "first release"
};
const prepare = (applied, workspace) => {
	const packages = new Map(workspace.map((entry) => [entry.name, entry]));
	return applied.map((release) => {
		const entry = packages.get(release.name);
		if (!entry) throw new Error(`release package ${release.name} is missing from the workspace snapshot`);
		const firstRelease = release.currentVersion === release.newVersion;
		return {
			name: release.name,
			path: entry.path,
			from: firstRelease ? void 0 : release.currentVersion,
			to: release.newVersion,
			kind: firstRelease ? "new" : bumpType(release.currentVersion, release.newVersion),
			internal: entry.private
		};
	}).sort((a, b) => a.name.localeCompare(b.name));
};
const changelogDetails = (out, release) => {
	const transition = release.from ? `${release.from} &rarr; <b>${release.to}</b>` : `<b>${release.to}</b>`;
	out.push("<details>");
	out.push(`<summary><code>${release.name}</code> &nbsp;&middot;&nbsp; ${transition}</summary>`);
	out.push("");
	out.push("<br>");
	out.push("");
	out.push(changelogEntry(release.path, release.to) || "_No changelog entry recorded._");
	out.push("");
	out.push("</details>");
	out.push("");
};
const renderReleasePrBody = (applied, workspace) => {
	const prepared = prepare(applied, workspace);
	const releases = prepared.filter((release) => !release.internal);
	const internal = prepared.filter((release) => release.internal);
	const out = [];
	out.push("## Release summary");
	out.push("");
	if (releases.length === 0) out.push("No publishable packages were prepared for release.");
	else {
		const count = releases.length;
		out.push(`\`pnpm version -r\` consumed the pending change intents and prepared **${count}** package${count === 1 ? "" : "s"} for release.`);
		out.push("Merging this pull request publishes the versions listed below.");
		out.push("");
		out.push("| Package | Bump | Current | Next |");
		out.push("| :--- | :---: | ---: | ---: |");
		for (const release of releases) {
			const current = release.from ? `\`${release.from}\`` : "—";
			out.push(`| \`${release.name}\` | ${badge[release.kind]} | ${current} | \`${release.to}\` |`);
		}
		out.push("");
		out.push("### Changelogs");
		out.push("");
		for (const release of releases) changelogDetails(out, release);
	}
	if (internal.length > 0) {
		out.push("");
		out.push("### Internal packages");
		out.push("");
		out.push("Not published to npm.");
		out.push("");
		out.push("| Package | Bump | Current | Next |");
		out.push("| :--- | :---: | ---: | ---: |");
		for (const release of internal) {
			const current = release.from ? `\`${release.from}\`` : "—";
			out.push(`| \`${release.name}\` | ${badge[release.kind]} | ${current} | \`${release.to}\` |`);
		}
		out.push("");
		for (const release of internal) changelogDetails(out, release);
	}
	out.push("");
	return `${out.join("\n")}\n`;
};

//#endregion
//#region src/commands/release-pr-body.ts
const releasePrBody = {
	usage: "<releases.json> <workspace-list.json>",
	run: (argv) => {
		const [releasesPath, workspacePath] = argv;
		if (!releasesPath || !workspacePath) throw new Error("usage: release-pr-body <releases.json> <workspace-list.json>");
		process.stdout.write(renderReleasePrBody(parseAppliedReleases(readFileSync(releasesPath, "utf8")), parseWorkspacePackages(readFileSync(workspacePath, "utf8"))));
	}
};

//#endregion
//#region src/release-plan.ts
const MAX_ARTIFACT_BYTES = 1048576;
const MAX_PACKAGES = 100;
const PACKAGE_NAME = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
const PACKAGE_VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const record = (value, context) => {
	if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`${context}: expected an object`);
	return value;
};
const exactKeys = (value, expected, context) => {
	if (Object.keys(value).sort().join("\0") !== [...expected].sort().join("\0")) throw new Error(`${context}: expected only ${expected.join(", ")}`);
};
const stringField = (value, key, context) => {
	const field = value[key];
	if (typeof field !== "string") throw new Error(`${context}.${key}: expected a string`);
	return field;
};
const validateNameVersion = (name, version, context) => {
	if (name.length > 214 || !PACKAGE_NAME.test(name)) throw new Error(`${context}: invalid npm package name ${JSON.stringify(name)}`);
	if (!PACKAGE_VERSION.test(version)) throw new Error(`${context}: invalid npm package version ${JSON.stringify(version)}`);
};
const validatePlan = (plan) => {
	if (plan.contractVersion !== "" && !isReleaseVersion(plan.contractVersion)) throw new Error(`release plan: expected an empty or plain semver contract version, got ${JSON.stringify(plan.contractVersion)}`);
	if (plan.packages.length > MAX_PACKAGES) throw new Error(`release plan must contain at most ${MAX_PACKAGES} packages`);
	const names = /* @__PURE__ */ new Set();
	for (const [index, packageRelease] of plan.packages.entries()) {
		const context = `release plan.packages[${index}]`;
		validateNameVersion(packageRelease.name, packageRelease.version, context);
		if (names.has(packageRelease.name)) throw new Error(`${context}: duplicate package name ${JSON.stringify(packageRelease.name)}`);
		names.add(packageRelease.name);
	}
	return plan;
};
const createReleasePlan = (workspace, contractVersion = "") => validatePlan({
	contractVersion,
	packages: workspace.filter(isPublicWorkspacePackage).map(({ name, version }) => ({
		name,
		version
	})).sort((left, right) => left.name.localeCompare(right.name))
});
const parseReleasePlan = (source) => {
	if (Buffer.byteLength(source) > MAX_ARTIFACT_BYTES) throw new Error(`release plan exceeds ${MAX_ARTIFACT_BYTES} bytes`);
	const value = record(JSON.parse(source), "release plan");
	exactKeys(value, ["contractVersion", "packages"], "release plan");
	if (!Array.isArray(value["packages"])) throw new Error("release plan.packages: expected an array");
	const packages = value["packages"].map((entry, index) => {
		const context = `release plan.packages[${index}]`;
		const item = record(entry, context);
		exactKeys(item, ["name", "version"], context);
		return {
			name: stringField(item, "name", context),
			version: stringField(item, "version", context)
		};
	});
	return validatePlan({
		contractVersion: stringField(value, "contractVersion", "release plan"),
		packages
	});
};
const artifactDirectory = (path) => {
	const absolute = resolve(path);
	const metadata = lstatSync(absolute);
	if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error(`${path} must be a regular directory`);
	return realpathSync(absolute);
};
const createReleasePlanArtifact = (directoryPath, workspace, contractVersion = "") => {
	const directory = artifactDirectory(directoryPath);
	if (readdirSync(directory).length !== 0) throw new Error("release plan artifact directory is not empty");
	const plan = createReleasePlan(workspace, contractVersion);
	writeFileSync(resolve(directory, "release-plan.json"), `${JSON.stringify(plan)}\n`, {
		encoding: "utf8",
		flag: "wx",
		mode: 384
	});
	return plan;
};
const validateReleasePlanArtifact = (directoryPath) => {
	const directory = artifactDirectory(directoryPath);
	const entries = readdirSync(directory);
	if (entries.length !== 1 || entries[0] !== "release-plan.json") throw new Error("release plan artifact must contain only release-plan.json");
	const planPath = resolve(directory, "release-plan.json");
	const metadata = lstatSync(planPath);
	if (!metadata.isFile() || metadata.isSymbolicLink() || metadata.size === 0 || metadata.size > MAX_ARTIFACT_BYTES) throw new Error(`release-plan.json must be a non-empty regular file of at most ${MAX_ARTIFACT_BYTES} bytes`);
	return parseReleasePlan(readFileSync(planPath, "utf8"));
};
const releasePlanWorkspace = (plan) => plan.packages.map(({ name, version }) => ({
	name,
	version,
	path: ".",
	private: false
}));

//#endregion
//#region src/commands/release-plan.ts
const manifestVersion$1 = (packagePath) => {
	const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
	if (typeof manifest !== "object" || manifest === null || Array.isArray(manifest)) throw new Error(`${packagePath}: expected a package manifest object`);
	const version = manifest["version"];
	if (typeof version !== "string") throw new Error(`${packagePath}: expected a string version field`);
	return version;
};
const releasePlan = {
	usage: "create <workspace-list.json> <artifact-directory> [<contract-package.json>] | validate <artifact-directory> <workspace-output.json>",
	run: (argv) => {
		const [operation, firstPath, secondPath, thirdPath, ...unexpected] = argv;
		if (operation === "create" && firstPath && secondPath && unexpected.length === 0) {
			const workspace = parseWorkspacePackages(readFileSync(firstPath, "utf8"));
			createReleasePlanArtifact(secondPath, workspace, thirdPath ? manifestVersion$1(thirdPath) : "");
			return;
		}
		if (operation === "validate" && firstPath && secondPath && thirdPath === void 0 && unexpected.length === 0) {
			const plan = validateReleasePlanArtifact(firstPath);
			writeFileSync(secondPath, `${JSON.stringify(releasePlanWorkspace(plan))}\n`, {
				encoding: "utf8",
				flag: "wx",
				mode: 384
			});
			process.stdout.write(`contract_version=${plan.contractVersion}\n`);
			return;
		}
		throw new Error("usage: release-plan create <workspace-list.json> <artifact-directory> [<contract-package.json>] | validate <artifact-directory> <workspace-output.json>");
	}
};

//#endregion
//#region src/shared-workflows.ts
const renderSharedReleaseBody = ({ repository, version, sha, workflows, changelog, notes }) => {
	const major = version.split(".")[0];
	const out = [];
	out.push("Shared GitHub Actions workflows. Add one job per workflow to a caller in");
	out.push("`.github/workflows/`, pinned to this commit:");
	out.push("");
	out.push("```yaml");
	for (const workflow of workflows) out.push(`uses: ${repository}/.github/workflows/${workflow}@${sha} # v${version}`);
	out.push("```");
	out.push("");
	out.push(`Ready-to-copy callers: [\`.github/workflows-examples\`](https://github.com/${repository}/tree/${sha}/.github/workflows-examples).`);
	out.push("");
	out.push("Re-resolve this commit at any time:");
	out.push("");
	out.push("```sh");
	out.push(`gh api repos/${repository}/git/ref/tags/v${major} --jq .object.sha`);
	out.push("```");
	if (changelog?.trim()) {
		out.push("");
		out.push("## Changes");
		out.push("");
		out.push(changelog.trim());
	}
	if (notes?.trim()) {
		out.push("");
		out.push("---");
		out.push("");
		out.push(notes.trim());
	}
	return `${out.join("\n")}\n`;
};
const sharedWorkflowReleasePending = async (api, version) => {
	if (!isReleaseVersion(version)) throw new Error(`expected a plain semver version, got "${version}"`);
	return !await api.releaseExists(`v${version}`);
};
const putTag = async (api, tag, sha, force) => {
	const created = await api.createRef(`refs/tags/${tag}`, sha);
	if (created.ok) return true;
	if (!force) {
		console.error(`failed to create tag ${tag}:`, created.payload);
		return false;
	}
	const updated = await api.updateRef(`refs/tags/${tag}`, sha);
	if (updated.ok) return true;
	console.error(`failed to move tag ${tag}:`, updated.payload);
	return false;
};
const releaseSharedWorkflows = async ({ api, sha, version, packagePath, workflows }) => {
	if (!isReleaseVersion(version)) throw new Error(`expected a plain semver version, got "${version}"`);
	if (workflows.length === 0) throw new Error("no shared-*.yml workflows found");
	const tag = `v${version}`;
	if (!await sharedWorkflowReleasePending(api, version)) {
		console.log(`${tag} already released, nothing to do`);
		return;
	}
	const releases = await api.listReleases();
	if (!await api.tagExists(tag) && !await putTag(api, tag, sha, false)) throw new Error(`could not create ${tag}`);
	if (!await putTag(api, `v${version.split(".")[0]}`, sha, true)) throw new Error(`could not move the major tag for ${tag}`);
	const previousTag = releases.filter((release) => isReleaseVersion(release.tag_name.replace(/^v/, ""))).sort((a, b) => b.created_at.localeCompare(a.created_at))[0]?.tag_name ?? "";
	const created = await api.createRelease({
		tag,
		name: `Shared workflows ${tag}`,
		body: renderSharedReleaseBody({
			repository: api.repository,
			version,
			sha,
			workflows,
			changelog: changelogEntry(packagePath, version),
			notes: await api.generateNotes(tag, sha, previousTag)
		}),
		prerelease: false
	});
	if (!created.ok) throw new Error(`failed to create release ${tag}: ${JSON.stringify(created.payload)}`);
	console.log(`created release ${tag} at ${sha}`);
};

//#endregion
//#region src/commands/shared-workflows-release.ts
const manifestVersion = (packagePath) => {
	const manifest = JSON.parse(readFileSync(packagePath, "utf8"));
	if (typeof manifest !== "object" || manifest === null || !("version" in manifest)) throw new Error(`${packagePath} has no version field`);
	const { version } = manifest;
	if (typeof version !== "string") throw new Error(`${packagePath}: expected a string version, got ${JSON.stringify(version)}`);
	return version;
};
const sharedWorkflowsRelease = {
	usage: "<package.json> <workflows-dir> | pending <version>",
	run: async (argv) => {
		if (argv[0] === "pending") {
			const [, version, ...unexpected] = argv;
			if (!version || unexpected.length > 0) throw new Error("usage: shared-workflows-release pending <version>");
			const pending = await sharedWorkflowReleasePending(apiFromEnv(), version);
			process.stdout.write(`pending=${pending}\n`);
			return;
		}
		const [packagePath, workflowsDir] = argv;
		if (!packagePath || !workflowsDir) throw new Error("usage: shared-workflows-release <package.json> <workflows-dir>");
		await releaseSharedWorkflows({
			api: apiFromEnv(),
			sha: requireEnv("GITHUB_SHA"),
			version: manifestVersion(packagePath),
			packagePath: dirname(packagePath),
			workflows: readdirSync(workflowsDir).filter((file) => file.startsWith("shared-") && file.endsWith(".yml")).sort()
		});
	}
};

//#endregion
//#region src/commands/signed-commit.ts
const signedCommit = {
	usage: "<branch> <message> <base-oid> <artifact-directory>",
	run: async (argv) => {
		const [branch, message, baseOid, artifactDirectory] = argv;
		if (!branch || !message || !baseOid || !artifactDirectory) throw new Error("usage: signed-commit <branch> <message> <base-oid> <artifact-directory>");
		const artifact = readReleasePrArtifact(artifactDirectory);
		const oid = await createSignedCommit({
			api: apiFromEnv(),
			baseOid,
			branch,
			message,
			changes: artifact.changes
		});
		console.log(`created signed commit ${oid}`);
	}
};

//#endregion
//#region src/commands/index.ts
const commands = {
	"contract-version": contractVersion,
	"github-releases": githubReleases,
	"npm-publishing-mode": npmPublishingMode,
	"package-artifact": packageArtifact,
	"release-pr-artifact": releasePrArtifact,
	"release-pr-body": releasePrBody,
	"release-plan": releasePlan,
	"shared-workflows-release": sharedWorkflowsRelease,
	"signed-commit": signedCommit
};
const usage = () => [
	"usage: gha.mjs <command> [args]",
	"",
	...Object.entries(commands).map(([name, command]) => `  ${name} ${command.usage}`)
].join("\n");

//#endregion
//#region src/cli.ts
const [name, ...argv] = process.argv.slice(2);
const command = name === void 0 ? void 0 : commands[name];
if (!command) {
	console.error(usage());
	process.exit(1);
}
try {
	await command.run(argv);
} catch (error) {
	console.error(error);
	process.exitCode = 1;
}

//#endregion
export {  };