// Copies the bundled CLI into .github/scripts, where the shared workflows run it
// straight from a checkout. The output is committed so a change to the tooling
// is visible to the release-intent guard in CI.
//
// Runs under Node's type stripping, so keep the syntax erasable.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const BANNER =
  "// Generated by `pnpm --filter @zemd/gha run build` from internal/gha/src. Do not edit.\n";
const BUNDLE = "gha.mjs";

const dist: string = fileURLToPath(new URL("../dist/", import.meta.url));
const target: string = fileURLToPath(new URL("../../../.github/scripts/", import.meta.url));
const bundle: string = join(dist, BUNDLE);

if (!existsSync(bundle)) {
  throw new Error(`${bundle} is missing, run tsdown first`);
}

mkdirSync(target, { recursive: true });

// Drops files left behind by an earlier output layout.
for (const file of readdirSync(target)) {
  if (file !== BUNDLE) {
    rmSync(join(target, file), { recursive: true });
  }
}

writeFileSync(join(target, BUNDLE), BANNER + readFileSync(bundle, "utf8"));

console.log(`synced ${BUNDLE} to .github/scripts`);
