// Synchronizes the bundled CLI into .github/scripts, where shared workflows run
// it straight from a checkout. The output is committed so tooling changes stay
// visible to the release-intent guard in CI.
//
// Runs under Node's type stripping, so keep the syntax erasable.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const GENERATED_BANNER: string =
  "// Generated by `pnpm --filter @zemd/gha run sync` from internal/gha/src. Do not edit.\n";
export const BUNDLE_FILENAME = "gha.mjs";
export const SYNC_INSTRUCTION = "pnpm --filter @zemd/gha run sync";

export type SyncMode = "check" | "write";

export interface SyncPaths {
  readonly distDirectory: string;
  readonly targetDirectory: string;
}

export interface SyncIo {
  readonly log: (message: string) => void;
  readonly error: (message: string) => void;
}

export const defaultSyncPaths: SyncPaths = {
  distDirectory: fileURLToPath(new URL("../dist/", import.meta.url)),
  targetDirectory: fileURLToPath(new URL("../../../.github/scripts/", import.meta.url)),
};

const defaultIo: SyncIo = {
  log: (message: string): void => console.log(message),
  error: (message: string): void => console.error(message),
};

export const parseSyncMode = (args: readonly string[]): SyncMode => {
  if (args.length === 0) return "write";
  if (args.length === 1 && args[0] === "--check") return "check";
  throw new Error(`Unknown sync argument(s): ${args.map((arg) => JSON.stringify(arg)).join(" ")}`);
};

export const expectedBundleContents = (paths: SyncPaths): Buffer => {
  const bundlePath = join(paths.distDirectory, BUNDLE_FILENAME);
  if (!existsSync(bundlePath)) {
    throw new Error(
      `${bundlePath} is missing. Run \`${SYNC_INSTRUCTION}\` to build and synchronize it.`,
    );
  }
  return Buffer.concat([Buffer.from(GENERATED_BANNER, "utf8"), readFileSync(bundlePath)]);
};

const unexpectedEntries = (paths: SyncPaths): string[] => {
  if (!existsSync(paths.targetDirectory)) return [];
  return readdirSync(paths.targetDirectory)
    .filter((entry) => entry !== BUNDLE_FILENAME)
    .sort();
};

export const checkSynchronizedBundle = (paths: SyncPaths = defaultSyncPaths): void => {
  const expected = expectedBundleContents(paths);
  const targetBundle = join(paths.targetDirectory, BUNDLE_FILENAME);
  const issues: string[] = [];

  if (!existsSync(targetBundle)) {
    issues.push(`missing ${targetBundle}`);
  } else if (!readFileSync(targetBundle).equals(expected)) {
    issues.push(`stale ${targetBundle}`);
  }

  const unexpected = unexpectedEntries(paths);
  if (unexpected.length > 0) {
    issues.push(
      `unexpected generated entries: ${unexpected.map((entry) => JSON.stringify(entry)).join(", ")}`,
    );
  }

  if (issues.length > 0) {
    throw new Error(
      `The committed GHA bundle is not synchronized (${issues.join("; ")}). Run \`${SYNC_INSTRUCTION}\` and commit the result.`,
    );
  }
};

export const writeSynchronizedBundle = (paths: SyncPaths = defaultSyncPaths): void => {
  const expected = expectedBundleContents(paths);
  mkdirSync(paths.targetDirectory, { recursive: true });
  for (const entry of unexpectedEntries(paths)) {
    rmSync(join(paths.targetDirectory, entry), { recursive: true });
  }
  writeFileSync(join(paths.targetDirectory, BUNDLE_FILENAME), expected);
};

export const runSyncCli = (
  args: readonly string[],
  paths: SyncPaths = defaultSyncPaths,
  io: SyncIo = defaultIo,
): number => {
  try {
    const mode = parseSyncMode(args);
    if (mode === "check") {
      checkSynchronizedBundle(paths);
      io.log(`verified ${BUNDLE_FILENAME} in .github/scripts`);
    } else {
      writeSynchronizedBundle(paths);
      io.log(`synced ${BUNDLE_FILENAME} to .github/scripts`);
    }
    return 0;
  } catch (error) {
    io.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
};

const entrypoint = process.argv[1];
if (entrypoint !== undefined && pathToFileURL(resolve(entrypoint)).href === import.meta.url) {
  process.exitCode = runSyncCli(process.argv.slice(2));
}
