name: Fuzz PR

permissions: {}

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - "http-clients/**"
      - "internal/fuzz/**"
      - ".clusterfuzzlite/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/cflite_pr.yml"

concurrency:
  group: cflite-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzzing:
    name: Fuzz changed code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: none
          github-token: ${{ github.token }}

      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: none
          github-token: ${{ github.token }}
          fuzz-seconds: 300
          mode: code-change
          output-sarif: true
