name: Fuzz maintenance

permissions: {}

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

concurrency:
  group: cflite-cron
  cancel-in-progress: false

jobs:
  pruning:
    name: Corpus pruning
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: address

      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: address
          github-token: ${{ github.token }}
          fuzz-seconds: 600
          mode: prune

  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: coverage

      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          sanitizer: coverage
          github-token: ${{ github.token }}
          fuzz-seconds: 600
          mode: coverage
